### ISSUE TITLE
Custom terrain insets

### ISSUE THREAD

**Issue by kircher1** [microsoft/MapsSDK-Unity#1]
**Is your feature request related to a problem? Please describe.**
Overlaying custom terrain or building data conflicts with the terrain and building data on the MapRenderer.

**Describe the solution you'd like**
A terrain inset feature would allow for flattening regions of the map defined by GeoBoundingBoxes/Rectangles to either the ellipsoid or terrain surface. This would open up scenarios where one can replace the default terrain and/or buildings with a MapPin based model of their own.

**Comment by HKBSC** [comment]
We definitely need this feature. Would be great to be able to use a bounding box to subtract 3D data to insert our own. Would be even better if it could replace Buildings only or Terrain + Building.

**Comment by pundirmr** [comment]
Hi,
Any update on this?

**Comment by kpprt** [comment]
Hi, I would also be interested in this feature. Is there any update on this? We have the same idea to clip away certain parts of the map and replace them with a custom building attached to a pin.
