### ISSUE TITLE
Handling dynamic objects on map.

### ISSUE THREAD

**Issue by XR-Jaco** [microsoft/MapsSDK-Unity#104]
I'm trying to handle **dynamic objects**  visualization on top of map. The _MapPin_ component works great with static objects, but I would like also to handle and display dynamic objects (_e.g. an aircraft following a waypoint route_). The desired behaviour would be that when I pan o rescale the map everything is updated in real time. Can you suggest some strategy/approach? Thanks

**Comment by kircher1** [comment]
The MapPin's Center property (LatLon) can be updated at runtime. If the waypoints are latitude-longitude or a coordinate system that could be translated to LatLon, then having a script that update's the position of the pin each frame should do the trick.

Similarly, the MapPin's Altitude property can be updated at runtime. 

One thing to point out here is that if the MapPin's AltitudeReference property is set to Surface or Terrain (Surface is default), then this will require a more expensive computation to determine an altitude relative to the map's surface each time the LatLon changes. That may be acceptable for updating just one MapPin per frame, but it may get too expensive if there are many MapPins being updated each frame. In either case, if you can get away with using AltitudeReference Ellipsoid, which does not compute altitudes relative terrain surface and uses a simpler computation to determine altitude, then the perf overhead would be minimal. Whether or not Ellipsoid reference will work for the altitude values will depend on how the aircraft altitude's are specified.

**Comment by XR-Jaco** [comment]
I partially solved the problem. For objects that move along a **predefined path**, everything is fine. 
Instead, I have difficulties in dealing with dynamic objects that **do not follow a predetermined path**, such a **missile** directed towards a moving target.  Suppose that my missile evolves over time with instructions like  __transform.Translate()_ that directly manipulate the transform. 
Should I convert everything so that it returns a Vector3 Position to be assigned  to a MapPin? 
I'm afraid it can be a very heavy computation.

**Comment by kircher1** [comment]
This is a good scenario but a tricky one to solve, so I went ahead and made a quick prototype to demonstrate one way to accomplish it.

At a high level, the idea is to generate MapPins for the dynamic objects.

Here's a [gist](https://gist.github.com/kircher1/fa9e54f9ca9948bafba12a23e5f83e0d) with two relevant scripts.

Using the scripts:
1) Create a prefab with a MapPin component. Place a MapPinAnimator component on the same GameObject. Set the Velocity field of MapPinAnimator something reasonable, say 20 meters per second*.
2) Add a MapPin to the MapRenderer at some location you want to generate pins from. Then add a MapPinGenerator component to this object. Set the "Dynamic Object" field of the MapPinGenerator to the prefab created in step 1. 

_*The velocity used by the MapPinAnimator is in real world meters. What I mean by that is if you wanted to animate a car moving 
 along the map surface at 20 meters per second, the value for the velocity would be 20._

When put together, this is what it looks like. Note how the moving spheres positions and velocity scale and translate consistently as the map is moved around:

https://user-images.githubusercontent.com/20366429/102545354-fcfbbf00-406a-11eb-9408-78f3248eec5b.mp4

**Comment by kircher1** [comment]
One remaining issue with this approach is that because the dynamic objects are MapPins, they will be deactivated if they move out of the MapRenderer's bounds. Not ideal probably, so I think a good enhancement to the SDK would be to add some sort of flag to [MapPin](https://github.com/microsoft/MapsSDK-Unity/blob/master/SupportingScripts/Runtime/Scripts/MapRenderer/MapPin/MapPin.cs) that indicates if it should be disabled when out of view. [MapRenderer](https://github.com/microsoft/MapsSDK-Unity/blob/master/SupportingScripts/Runtime/Scripts/MapRenderer/MapRenderer.cs) and [MapPinLayer](https://github.com/microsoft/MapsSDK-Unity/blob/master/SupportingScripts/Runtime/Scripts/MapRenderer/MapPin/MapPinLayer.cs) would then need to read this property to determine whether or not to deactivate the object when it's outside the map's bounds.
