### ISSUE TITLE
Different shader automatically used for Block vs Cylinder modes? 

### ISSUE THREAD

**Issue by yosun** [microsoft/MapsSDK-Unity#106]
**Describe the bug**
In Block Mode, I'm trying to render without the black jagged edges, as seen in the Cylinder Mode. However, it seems that switching modes switches shader(?) 

**To Reproduce**
1. Switch from Block to Cylinder mode and zoom in and out to notice the black edges that is present in Block but not Cylinder Modes 
 

**Expected behavior**
The unlit textures without black jagged edges in Cylinder Mode should be available in Block Mode

**Screenshots**
https://gyazo.com/0af8d0880c99e737d757248a5bb762b3

[![Image from Gyazo](https://i.gyazo.com/0af8d0880c99e737d757248a5bb762b3.gif)](https://gyazo.com/0af8d0880c99e737d757248a5bb762b3)

**Environment (please complete the following information):**
 - Unity version: [e.g. 2019.4.8f1]
 - Maps SDK Package version: [e.g. 0.10.1]

**Comment by kircher1** [comment]
A different shader variant is used for block and cylinder moders, but it's the same underlying shader. Basically, when in cylinder mode, ENABLE_CIRCULAR_CLIPPING define is set on the shader.

One of the views in the gif looks like triangle mesh debug view in the scene, or are you using a custom shader?

**Comment by yosun** [comment]
Ah, I wasn't aware that was a mesh debug view - is there a way to turn it off?

**Comment by kircher1** [comment]
![image](https://user-images.githubusercontent.com/20366429/102855784-1ccc1380-43da-11eb-98f9-f6b0ba227e5e.png)

Make sure that option is set to shaded, not shaded wireframe. Although if you are seeing this in the Game view, that's not the issue.

**Comment by yosun** [comment]
Hmmm... That doesn't seem to be the issue - I'm seeing the black lines on shaded in both game and scene views for Block Mode.   https://gyazo.com/bddc7b0085cea44e7162bf323caf7145 

Which version of Unity are you using?

**Comment by kircher1** [comment]
Most recent Unity version I've used is 2019.4.17. 

I suspect it may be some combination of Unity settings leading to this, but I haven't seen it before. If there is anything related to the graphics settings that you've tweaked off of the defaults, let me know. That, or maybe there is some other asset in the project causing this.

Does it also show up in final builds, or just the editor?

**Comment by kircher1** [comment]
A bit of a stale issue here, but we've seen this when running Unity on Mac. So it seems to be a Unity bug, and if it repros in player builds, I suggest filing a bug for Unity to investigate. MacOS itself though is not a target platform for the SDK.
