### ISSUE TITLE
Vision like from a motorcycle's handlebar

### ISSUE THREAD

**Issue by AhmedX6** [microsoft/MapsSDK-Unity#107]
Hello,
We would like to implement a racing game. We're using Unity. The goal is to have a realistic road of the Peripherique of Paris : https://www.google.com/maps/@48.8187305,2.3316843,3a,75y,294.27h,83.19t/data=!3m6!1e1!3m4!1sPkpSI2U5CiIjOfuXthVpww!2e0!7i16384!8i8192
We would like to be able to drive on the road like we're on it in real.

How can we proceed please ?

Thanks a lot,
Ahmed

**Comment by davidpmontesNASA** [comment]
I believe your question is merely a general application development question and not specific to the MapsSDK.  The answer to your question would involve placing the camera at the correct position relative to the map to simulate the perspective.  You are also able to dynamically update the map's location.  A combination of these two actions should answer your question.

**Comment by kircher1** [comment]
[Immersive mode](#2) would unlock this scenario.
