### ISSUE TITLE
Tile Layer Stuck On Map/Can't be completely removed

### ISSUE THREAD

**Issue by ChenZhipu** [microsoft/MapsSDK-Unity#109]
**Describe the bug**
Once the Aerial Imagery Type Default Texture Tile Layer is loaded and cached, switching it to symbolic or uncheck the default layer will not completely remove the Aerial layer. I do not know how to clear the cached map tiles.

**To Reproduce**
1. Run the map renderer in Unity. Enable Aerial Imagery Type in Default Texture Tile Layer.
2. Let Map fully load and cache by zooming in and out
3. Switch to symbolic Imagery Type in Default Texture Tile Layer. Or, disable the Default Texture Tile Layer, Or, add an Http Texture Tile Layer and place it on top of the Default Texture Tile Layer(in editor it should be under the Default Texture Tile Layer).
4. See error(Default Texture Tile Layer with Aerial Imagery Type stuck on Map, some tiles are showing on top of the Http Texture Tile Layer)

**Expected behavior**
Unwanted tile layer completely cleaned on map renderer when disabled.

**Screenshots**
Ignore the black squares. They are intended.
![image](https://user-images.githubusercontent.com/66401899/112554308-7149ab00-8d9c-11eb-9ef5-b262502af697.png)
Red lines are from an Http Texture Tile Layer, somewhere disappears in this zoom level.
![image](https://user-images.githubusercontent.com/66401899/112554343-7c044000-8d9c-11eb-8296-787796cbd658.png)
Red lines are from an Http Texture Tile Layer, fully shown in this zoom level.
![image](https://user-images.githubusercontent.com/66401899/112554413-a35b0d00-8d9c-11eb-8333-b907f6a719e3.png)
Layer sticks on the map even it is disabled.

**Environment (please complete the following information):**
 - Unity version: [e.g. 2019.4.22f1 and earlier]
 - Maps SDK Package version: [0.10.1 and earlier]

**Additional context**
Issue is there all the time, from the first day of using BingMaps SDK.

**Comment by kircher1** [comment]
This because the 3D city data takes priority over the texture tile layers... Unfortunately there's no way to make the textures overlay the 3D city data... If you don't need the 3D cities, you could disable them by switching the terrain mode to [Elevated](https://github.com/microsoft/MapsSDK-Unity/wiki/Configuring-the-MapRenderer#map-terrain-type). Then the textures should show up.
