### ISSUE TITLE
Where to display copyright text in an immersive-like implementation?

### ISSUE THREAD

**Issue by MMitty** [microsoft/MapsSDK-Unity#110]
Hello,

First of all, let me tell that the Maps SDK is really promising, and worked quite well in my tests so far. (Though it probably introduced seldom crashes to the editor.)

I read the Wiki about the need of displaying the copyright text, but the Wiki doesn't really handle the situation of immersive mode:

> The copyright text must be displayed in a conspicuous manner, near in proximity to the map.

Of course, immersive mode is not available yet, but in anticipation I faked it by enlarging a map object for flying an aircraft among some skyscrapers.

There are three kinds of views in this app: pilot view, follow cam and VR pilot view (Oculus Rift). 

When, where and how should the copyright text be displayed in the above situation?
Does it need to be continuously displayed or perhaps in the menus or scene loading screen only?

**Comment by cmumme** [comment]
This is also something I'd love to be answered, as I'm planning on using immersive mode (or maybe making my own implementation using the API provided by the sdk, if at all possible) as a core part of an upcoming game.

**Comment by kircher1** [comment]
The guidance around copyright text placement here hasn't changed. You could customize the display if the default location isn't working. See here: https://github.com/microsoft/MapsSDK-Unity/wiki/Customizing-copyrights-display
