### ISSUE TITLE
Disable Vertical Surface Placement Animation

### ISSUE THREAD

**Issue by MMitty** [microsoft/MapsSDK-Unity#111]
Hi,

I am looking for  a way to disable the vertical surface placement animation which happens during the initialization/loading process.
Is there a setting to do that? This is not a MapScene from point to point animation .

What I am trying to achieve:
- move the map couple hundred meters below Unity zero level
- start loading a map
- as soon as the elevation data arrives (any callback to catch this moment?), have a MapPin at the map center's Surface 0m altitude
- position the map vertically up so that the MapPin at Surface 0m altitude would be at Unity 0m.

**Comment by kircher1** [comment]
If the ElevatonTileLayer is disabled, the automatic displacement won't happen since the elevation data is what is used to do this... Of course if you want elevation data on your map, disabling it isn't really an option! We'll have to add an API for this.

**Comment by kircher1** [comment]
I should have also mentioned, you can use [`WaitForMapLoaded`](https://github.com/microsoft/MapsSDK-Unity/wiki/Microsoft.Maps.Unity#maprenderer) to determine when the map has completed loading of the data in view. So that is another option, hide the map in some way until the loaded coroutine is complete.

**Comment by MMitty** [comment]
Thanks for the response.
I do need elevation data as I am using the SDK to display the 3D world. And I'm already using the WaitForMapLoaded for some delay functions, so I'll try to use it for this, too.
It's just that loading the complete map takes some time and it would be better for me to display the map while partially loaded, just without the vertical jumps.

**Comment by kircher1** [comment]
The vertical surface displacement is needed in most scenarios. I think the best option for this case is to wait for the map to load.
