### ISSUE TITLE
2D Map in uGui? Or Custom Clip Boundary?

### ISSUE THREAD

**Issue by MMitty** [microsoft/MapsSDK-Unity#112]
Hi,

I checked out the 2DMapExample sample scene with hopes to use a map in a Unity GUI ( uGui, inside a canvas hierarchy) but the example did not put the map into GUI.

I'm making PC flight simulation where the aircraft dashboard has an LCD display for the map and all sorts of gauges overlaid over the map.  Actually, the LCD is a 3D iPad model fixed in front of the pilot inside the simulation.

Before trying the Maps SDK I used a "static" terrain model and used a large texture for the uGui map which I created in the Unity sceneview by manually saving a screenshot from a top-down ortho camera. But with the Maps SDK it is possible to go to arbitrary scenery locations and I can't take manual screenshots for these in advance.

I couldn't find any way so far reading through the issues here on GitHub to make a Maps SDK map a real uGui element. Is it possible somehow?

Perhaps the normal mesh map could be positioned at the screen plane of the iPad just below the uGui overlays, ~~but how could I clip the map extents outside the iPad screen~~? ( I realized meanwhile that the Local Map Dimension values are not integers as I thought thus it is easy to adjust the map sides aspect ratio to the iPad screen. I'd still be interested in the above uGui realated question...)  <--- Edit: This way of clipping is still not enough as the map needs to be rotated inside the iPad, so that the forward direction would point upwards on the screen, not the north direction. So the clipping boundaries would need to be  independent of the map rotation.

**Comment by kircher1** [comment]
I'm not sure what goes into making a proper Unity GUI element versus rendering a regular sort of GameObject. More research would be required there.

LocalMapDimension values are in map GameObject's local space, so correct, still floats (in local meters, not pixels).

The clipping problem is a bit trickier since you can't rotate the map's content itself (rather you have to rotate the entire GameObject). The only way I can imagine to solve this is to override the map shader with a custom version that applies some additional clipping (discards) to map fragments that are outside the iPad's bounds.

**Comment by MMitty** [comment]
[Unity GUI](https://docs.unity3d.com/2018.4/Documentation/Manual/UISystem.html) (or uGui) I suppose could use the UI Image or rather the UI Raw Image component.
The Raw Image takes a texture and displays it in the UI hierarchy. There is a Mask component which slices off parts of its children outside the mask area, so rotating and masking a uGui map would be a breeze.

**Comment by MMitty** [comment]
I'd like to add that there are a lot of uGui map solutions on the Unity Asset Store, even Bing Maps based, so it should be doable.
It would still be nice to us this single Maps SDK.

**Comment by MMitty** [comment]
I thought to cut short this topic and bought [Advanced Dissolve](https://assetstore.unity.com/packages/vfx/shaders/advanced-dissolve-111598) from the Unity Asset Store to have cutting volumes like this:
[https://www.youtube.com/watch?v=EqEb6FgUlGA](url)
I found out that this does not work just by setting an Advanced Dissolve material as custom terrain material, only the white/grey grid is shown, no map terrain textures.
@kircher1 Is there an easy fix for this, what do you think?

**Comment by kircher1** [comment]
The map's terrain shader itself is custom so while it could be possible to use that dissolve effect with the map, it would require modifying that dissolve shader to support the map related functionality (or vice-versa).

To clip the map's pixels to a different/additional mask, to be more specific, some additional clipping logic is needed in the [StandardTerrainShader](https://github.com/microsoft/MapsSDK-Unity/blob/master/SupportingScripts/Runtime/Shaders/StandardTerrainShader-MapsSDK.shader)'s frag shader.

```
// Existing code: Clip to ClippingVolume
float minDistanceToPlane = ClipToVolume(i.worldPosition, i.isSkirt);
               
// New code: Clip to iPad scren extents. CustomClipping function would need to read some shader properties
// to determine the clipping extents (in world space here) and then discard the pixels accordingly.
CustomClipping(i.worldPosition);
```

To go about that, copy the StandardTerrainShader-MapsSDK.shader to your projects Asset folder, rename it, and create a new Material based on it. Use that Material for the MapRenderer's custom TerrainMaterial. Modifications can then be made to this copy of the shader.

**Comment by MMitty** [comment]
Thanks, I'll try to look at it, though as I'm a complete shader beginner, I'll probably just put a camera above the terrain and direct its image into a render texture which I'll put inside a UI RawImage component.
