### ISSUE TITLE
Map Limits

### ISSUE THREAD

**Issue by adamhill** [microsoft/MapsSDK-Unity#114]
Are there any docs or guidance on the size limits for Maps?  Both in GameObject size and geographic extents. 

I am looking for info specifically on non-desktop apps. Are there any tunable LOD parameters or other ways to thin geometry or textures? How severe are the limits going to be on the Hololens?

I am assuming there is nothing like ROAM implemented that would let stretch the map horizon to horizon?

Thanks.

**Comment by TerraSame** [comment]
Hello... I have experimented at length of this matter.
What you can do, if you are using a game engine like Uinty etc, is scale
the map to your desired size.
Then set the zoom level. Unfortunately, when you zoom way out, the 3d
aspect can become un-noticeable...
I don't believe you can set the LOD switching. I  suppose if you could,
there would be a very low frame rate with too many vertices, polys and HQ
Textures...
I have also found that if you, for example, make a smaller terrain, then
copy it and shift it over then revise either the Lat or Long, you can have
multiple terrains.
If you do that, be careful not to choose two or more terrains as they will
all shift to look like the original thus lossing a bunch of work.
Also when doing this, frame rate can suffer and load time as well. And I
suppose the ticker could add where a problem could creep up on you or the
client.
Just what I noticed possible... I imagine Brian will chime in with a
definitive response.
Best of luck

**Comment by kircher1** [comment]
Correct, the map does not render using ROAM or any sort of dynamic LOD'ing scheme. It chooses the LOD of the data it's rendering based on the current zoom level modified by some quality knob (see below)... But, this is why the map's dimension is constrained. Increasing the size quickly becomes unwieldy, where it could require thousands of draw calls to render the map.

Here are some pointers:
* [Increasing or decreasing the quality of the map](https://github.com/microsoft/MapsSDK-Unity/wiki/Configuring-the-MapRenderer#quality-settings).
* Geographic extents of the current map view can be queried from the [Bounds](https://github.com/microsoft/MapsSDK-Unity/wiki/Microsoft.Maps.Unity#maprendererbase)

So you can't stretch the map from horizon to horizon. The closest you could get is to max out the map's dimensions, and then apply a scaling factor to scale the map to it's true real-world size in meters (this will also require undoing Mercator scaling as well).

**Comment by kircher1** [comment]
Duping this to immersive mode request. #2
