### ISSUE TITLE
mapRenderer.Raycast Does Not Work If Ray Origin Is Inside The Map Object's Bounding Box

### ISSUE THREAD

**Issue by MMitty** [microsoft/MapsSDK-Unity#115]
**Describe the bug**
I am trying to use [mapRenderer.Raycast](https://github.com/microsoft/MapsSDK-Unity/wiki/Microsoft.Maps.Unity#maprendererraycasthit) and it sometimes works, sometimes not. It doesn't work if the ray origin is inside the bounding box of the map object. You can see the bounding box if you turn on Map Collider Type - Full Extents.

**To Reproduce**
1. Create a default map (the 3D world type).
2. Write a script according to the tutorial:
https://github.com/microsoft/MapsSDK-Unity/wiki/Raycasting-the-map
3. Determine the bounding box for the map object visually using the Map Collider Type = Full Extents.
4. Try raytracing downwards from a point outside the bounding box -> it will work.
5. Try raytracing downwards from a point inside the bounding box but above the surface -> it will not work. The raytrace bool will be false.

**Expected behavior**
Raycast should work even if the ray origin is inside the map object bounding box.

**Screenshots**
None.

**Environment:**
 - Unity version: 2018.4.3f1
 - Maps SDK Package version: 0.10.1

**Additional context**
None.

**Comment by kircher1** [comment]
Hi @MMitty, can you share the lat-lon and zoom level you were able to repro this issue at? I've tried some areas where ray origin is inside the map's bounds and I'm still getting valid raycast results back.

**Comment by MMitty** [comment]
If I have to provide one location, this would be one:

37.80246847633425, -122.4614082186138
zoom level 20

Otherwise this happens around this wider area ( ~500m radius), didn't try
to go far from here. I am always using zoom level 20, and doing a raycast
downwards on a certain map object to test for altitude above ground surface.

The complete picture includes that there are several other overlapping map
objects there with the same placement and location but different zoom
levels, but I doubt that this matters as I specify my particular map object
in the raycast function.

**Comment by kircher1** [comment]
Hi @MMitty, I've still had no luck reproing this. I've tried scaling up and down the map transform as well, and the raycast works in that area when I put the camera inside the map's bounds. 

You already mentioned this isn't the case, but if the ray origin starts below the map surface itself, then the raycast will not return a result and that's expected.
