### ISSUE TITLE
Viewing OBJ/FBX/GLTF files in the Map Renderer

### ISSUE THREAD

**Issue by AC0793** [microsoft/MapsSDK-Unity#116]
I have an FBX file from photogrammetry that I have imported into Unity alongside the Map Renderer. I'm interested in being able to navigate and interact with the 3D FBX mesh inside of the square Map Renderer. Is that possible now or could that be an option in the near future?
![UnityClintonCapture copy](https://user-images.githubusercontent.com/10778132/114102619-3d3ab380-988d-11eb-9846-12fedda2a177.PNG)

**Comment by TerraSame** [comment]
Sounds like a Unity question to me...
I would imagine you can just give it a physics mesh so you can walk or what
ever on your fbx... I am sure Brian will address this question but you
might want to be a little more specific...

**Comment by AC0793** [comment]
@TerraSame It could be more of a Unity question, but i'm specifically curious about interacting with the 3D mesh in a similar fashion as the Bing Map data source in the map renderer. Could I somehow load the FBX or GLTF file in the map renderer to pan/drag/zoom across portions of it in the same way?

**Comment by kircher1** [comment]
Hi @AC0793, are you using MRTK/MixedRealityMapInteractionHandler? Generally though, any MapInteractionHandler could be implemented to do this. Instead of only looking for intersections with the map itself, the handler would need to check the children objects as well.

**Comment by AC0793** [comment]
@kircher1 I haven't used it yet, thanks for bringing it to my attention. I found the script you mentioned in one of the examples. Would this be the only script that I would attach to the FBX with its children? Or do I need other scripts like the Map Renderer working with this one to get the same square or cylindrical map shape?

**Comment by kircher1** [comment]
If you want to clip your mesh to the map itself, you'll need to use a custom shader for the material that renders the photogrammetric mesh, alongside a script that synchronizes some parameters for the map's clipping extents with the shader.

Check out [this gist](https://gist.github.com/kircher1/4a9e67b447979dabe41ed63643ac6bf0) for the shader and script.

You'll need to create a Material using that shader, Apply that Material to the MeshRenderer of the photogrammetric mesh. Then attach the `ApplyClippingVolumeProperties` component to that GameObject.

**Comment by AC0793** [comment]
@kircher1 Thanks for the gist. Going to test this soon. I’m not sure if I’m asking this right, but is the original map required underneath the photogrammetry or can this shader run in a similar fashion without the Bing Map loaded around it?

**Comment by kircher1** [comment]
@AC0793 The MapRenderer needs to be enabled for that script to work. If the default map surface will z-fight with your model, try using Terrain Type = Elevated under the MapRenderer's Render Settings.
