### ISSUE TITLE
MapPin hides the transform gizmo and the gizmo remains hidden

### ISSUE THREAD

**Issue by MMitty** [microsoft/MapsSDK-Unity#117]
**Describe the bug**
Clicking in the Hierarchy on a MapPin object captures and hides the transform gizmo and it will keep it hidden while choosing other objects until a MapRenderer object is selected again.

**To Reproduce**
1. In the Hierarchy panel click on a MapPin object which is a child of a MapRenderer. The transform Gizmo becomes invisible.
2. Click on any other non-MapRednerer object, and the transform gizmo will be still hidden. 
3. Click on a MapRenderer object, then the transform gizmo will again become visible.

**Expected behavior**
The MapPin hiding the transform gizmo is fine, but then clicking any other object should give the transform gizmo back.

**Screenshots**
None.

**Environment (please complete the following information):**
 - Unity version: 2018.4.3f1
 - Maps SDK Package version: 0.10.1

**Comment by kircher1** [comment]
@MMitty, I tried repro'ing on 2018.4.**34** but wasn't able to. Maybe this is fixed in newer Unity versions. Would you be able to upgrade your project to a newer version of 2018.4?

**Comment by MMitty** [comment]
Thanks for the suggestion. I am not going to upgrade engine version yet,
but when I'll do, I'll pay attention to this issue.
This isn't a breaking bug, fortunately.

**Comment by kircher1** [comment]
Please reopen if you see this in newer Unity versions.
