### ISSUE TITLE
Custom material for water surfaces

### ISSUE THREAD

**Issue by MMitty** [microsoft/MapsSDK-Unity#118]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a solution that would allow assigning custom watery/reflective materials to those parts of the 3D map that are water surfaces.

**Describe the solution you'd like**
I would like the option to set custom material to the water parts of the 3D surfaces. They could perhaps wear a separate material, or have a mask generated, or something else, I don't know the inner workings of the Maps plugin. Also, the water surfaces should be flat so the reflections could be uniform.

**Describe alternatives you've considered**
I tried to put a horizontal flat surface over the 3D map water surfaces, but the water surfaces are not really flat so the 3D map protruded above my flat surface at places. I couldn't raise my surface because then the things on the riverbank got covered at places.

**Additional context**
The desired effect:
![image](https://user-images.githubusercontent.com/81446773/114516557-cf500c80-9c3d-11eb-919c-4fade3342db5.png)

**Comment by kircher1** [comment]
Between the ability to customize the map material/shader and adding a custom TextureTileLayer, you could mask water areas and apply some special shading to "water" pixels. For getting tiles with custom styling, see [here](https://docs.microsoft.com/en-us/bingmaps/articles/custom-map-styles-in-bing-maps?msclkid=6f9c3245baa711ec8cc59a6d04e693d1#custom-map-styles-in-the-rest-and-tile-services).
