### ISSUE TITLE
Extend MapsSDK outside Unity

### ISSUE THREAD

**Issue by emepetres** [microsoft/MapsSDK-Unity#119]
Hi, first of all congratulations for the great work in the MapsSDK, develop access to bing maps capabilities is really interesting.

Me and my company ([Plain Concepts](https://www.plainconcepts.com)) would like to support the MapsSDK in our own graphics engine ([Wave Engine](https://waveengine.net/)). This engine is free to use, oriented to build business/industry applications, pure C#, and we think that adding the bing maps capabilities to it would be a great benefit.

As a Microsoft Gold Partner with more than 10 MVPs in our ranks we have already played with the Maps API, both the old one used by bing and the new one used in the MapsSDK. However, by looking at the Copyright notice and TOU, we are not sure if we are allowed to reverse engineer the API used by MapsSDK-Unity to create our own SDK.

Therefore we would like to colaborate with you in any way possible that allow us to integrate and use the MapsSDK in Wave, would that be possible? Some options of colaboration I can think of are:
* Have access to the SDK core and develop our own MapsSDK-Wave library
* Have access to the SDK core and create a more general MapsSDK library in .Net, open source
* Have access to the API documentation and build any of the previous options.

Please, let me know if that would be possible and any steps we should make in that direction. In negative case, would we at least be allowed to use the new API by reverse engineering it? In case you prefer to answer by email, my adress is jcarnero at plainconcepts.com

Thanks

**Comment by kircher1** [comment]
Hi @emepetres,

Thanks for reaching out. I recommend submitting this inquiry to the Bing Maps team using the contact [form](https://www.microsoft.com/en-us/maps/contact-us).

The core SDK here still has dependencies on Unity so isn't meant or intended to support other engines. There are also no plans currently to provide OSS code or libraries for pieces that would be needed for integration into a different engine.

Check the [terms of use](https://www.microsoft.com/en-us/maps/product) for what is allowed/not allowed. Section 5e refers to reverse engineering specifically.
