### ISSUE TITLE
MapPin.ShowOutsideMapBounds ignored by MapPinLayer

### ISSUE THREAD

**Issue by fra3point** [microsoft/MapsSDK-Unity#123]
[SDK version: 0.11.0]

The field MapPin.ShowOutsideMapBounds would be a very useful thing, if fully supported.
We plan to use it to fake large map overlays (i.e. hot areas, interest areas, etc) istead of providing custom layers, which happens to be quite difficult.

The checkbox shows up in the MapPin component's inspector, but it doesn't work at runtime.
Looking in the MapPinLayer script, I've found a comment (line 16) saying _**MapPin.ShowOutsideMapBounds is not used by the layer. Any out of view pin will be hidden.**_

Is this by design? Is there something I am missing?

**Comment by kircher1** [comment]
That's currently a limitation of the MapPinLayer. More work needs to be done to support this concept plus clustering.

ShowOutsideMapBounds field should have an affect when using MapPins that children of the MapRenderer GO (i.e. not using a MapPinLayer).
