### ISSUE TITLE
Set Bounds

### ISSUE THREAD

**Issue by amiiya** [microsoft/MapsSDK-Unity#124]
Hello there!

I really think this SDK is well done and the API reference is very useful.
I was wondering if it's possible to set the map bounds. I've found a get-method for this but not a setter.
I want to set the visible map area via bounds and not via zoom level which gives me more control over the visible section.

Thank you!
Celine

**Comment by kircher1** [comment]
That sort of API makes sense (setter for Bounds) and on a related note, a MapSceneOfBoundingBox would be good to add as well (used to animate to a bounds)-- similar logic used for both.

The idea of setting the map view to a bounds though is possible to do with the current API by setting Center and ZoomLevel to accommodate a bounding region, but it would require some math to compute the proper values for those properties. I'll try and share some logic for that later.

**Comment by kircher1** [comment]
```c#
        // Convert the target LatLon bounds to Mercator. This is a view of Crater Lake.
        var targetBounds = new GeoBoundingBox(new LatLon(42.899735, -122.180843), new LatLon(42.982423, -122.031155));
        var targetMercatorBounds = targetBounds.ToMercatorBoundingBox();

        // Compute the zoom level to use for viewing the bounds.
        var mapRenderer = GetComponent<MapRenderer>();
        var localMapDimension = mapRenderer.LocalMapDimension;
        var zoomLevelForXDimension = Math.Log(localMapDimension.x / targetMercatorBounds.Width, 2);
        var zoomLevelForYDimension = Math.Log(localMapDimension.y / targetMercatorBounds.Height, 2);
        var zoomLevel = (float)Math.Min(zoomLevelForXDimension, zoomLevelForYDimension) + 1;
        zoomLevel = Mathf.Clamp(zoomLevel, MapConstants.MinimumZoomLevel, MapConstants.MaximumZoomLevel);

        // Set center and zoom.
        mapRenderer.Center = targetBounds.Center;
        mapRenderer.ZoomLevel = zoomLevel;
```

**Comment by kircher1** [comment]
MapSceneOfBoundingBox added in 0.11.2. Use this to set the bounds of the MapRenderer.
