### ISSUE TITLE
Game mode shows black screen

### ISSUE THREAD

**Issue by minimalisticMe** [microsoft/MapsSDK-Unity#125]
Hi, I am using Unity `v2020.3.11f1` and want to view 2D maps.
I can successfully run example `2DMapExample`. Now I want to abstract it to my project.
I removed all input and interaction components from the example leaving only the Copyrights in the canvas:
![grafik](https://user-images.githubusercontent.com/13404680/124359754-a16bda00-dc26-11eb-85d6-4b55eaa243b5.png)
![grafik](https://user-images.githubusercontent.com/13404680/124359820-e1cb5800-dc26-11eb-82c9-34b84332c10f.png)

Next I made sure the sample project still runs, which it does.

Now I wanted to mirror the example to my project.
Adding `Add component` -> `Scripts` -> `Microsoft.Maps.Unity` -> `MapRenderer` like described in the documentation, adding the API-Key and setting all values and classes the same.
In Scene mode everything shows up just like in the sample, but my game mode doesn't show any maps.

What am I doing wrong?
What can I do to show output to the Game screen as well?

**Comment by kircher1** [comment]
Check that the Camera uses the same transform and settings in your project. If still not working, try copying over the 2DMapExample.unity (scene file) from the Sample Project to your new project, along with relevant scripts like MapStyleChangedHandler.cs/OrthoCameraMapDimensionSynchronizer.cs (maybe others). Then you can use that as a starting point in the new project.

**Comment by minimalisticMe** [comment]
Thank you very much!
The camera had the wrong z-value.
