### ISSUE TITLE
Failed to initialize the MapSession. Device may be offline.

### ISSUE THREAD

**Issue by atx-barnes** [microsoft/MapsSDK-Unity#126]
So I was able to use the maps SDK without any issues but today I've been getting this error every time I try to enter my developer key.

To reproduce, at least for me just try and enter your key in the inspector where you are supposed to.

**Expected behavior**
It should just work after my key is entered into the inspector field.

**Screenshots**

**Environment (please complete the following information):**
 - Unity version: 2019.4.28f1
 - Maps SDK Package version: 0.11.0
 
 Full Log below:
 
 `Failed to initialize the MapSession. Device may be offline.
=a5A=: Unable to complete SSL connection, 0, isHttpError: False, isNetworkError: True
  at =a8D=+=bafF=+=ba3C=.MoveNext () [0x0020b] in <0a8a7f80b84c4b0c9f79b1816f1316a4>:0 
`

**Comment by atx-barnes** [comment]
Maybe the servers were down because now it is working with no error shown above?

**Comment by atx-barnes** [comment]
I still sometimes have this error and can be annoying when trying to test in the editor. Does anyone know why this is happening?

**Comment by kircher1** [comment]
It's hard to say what the cause of this error is, but it would seem to be an issue related to the network connection.

The error message itself is being translated from the UnityWebRequest: `Unable to complete SSL connection.`

UnityWebRequest errors are categorized into "network errors" or "http errors". Http errors would have some 4xx or 5xx code associated with it. The error here however is a "network" error: (https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest-isNetworkError.html)
