### ISSUE TITLE
Cluster Map Pin script throws NullReferenceException

### ISSUE THREAD

**Issue by ctwarrick** [microsoft/MapsSDK-Unity#128]
**Describe the bug**
Attaching this component to a Unity GameObject causes Unity to throw NullReferenceExceptions in the console, and not display the UI for the Cluster Map Pin component

**To Reproduce**
1. Create Project in Unity with OpenXR, MRTK, and Maps SDK
2. Create an empty object and give it a MapRenderer component to make it a map
3. Give the map a MapPinLayer
3. Create a Cylinder object as a marker
4. Add the Cluster Map Pin component to the Cylinder
5. Observe NullReferenceExceptions being thrown at ClusterMapPinEditor.cs:27.  NullReferenceExceptions will continue to be thrown every time the mouse cursor moves within the Inspector.
6. Observe that the Cluster Map Pin component cannot display its fields in the Inspector.

**Expected behavior**
The Cluster Map Pin component is able to be edited in the Inspector.

**Screenshots**
![image](https://user-images.githubusercontent.com/83298584/126082418-33cf31ef-cb0e-4edf-88f5-570990ef1230.png)
![image](https://user-images.githubusercontent.com/83298584/126082446-b0c9e0a1-0351-4df5-b5b7-b4c77fc5043a.png)

**Environment:**
 - Unity version: 2020.3.14f1 Personal
 - MRTK Version: 2.7.2
 - Maps SDK Package version: 0.11.0
 - Mixed Reality OpenXR Plugin 1.0.1

**Comment by kircher1** [comment]
Thanks for filing an issue on this. There is a bug in the editor script that is causing the exception.

In the meantime, try switching the inspector view to debug mode to edit the script's fields:

![image](https://user-images.githubusercontent.com/20366429/126188153-c08ffbd2-83ef-430b-9400-66f0dab57701.png)

**Comment by kircher1** [comment]
Fixed in 0.11.1
