### ISSUE TITLE
Is Search.MapLocationFinder.FindLocations with position and boundingbox service working?

### ISSUE THREAD

**Issue by Nalistic36** [microsoft/MapsSDK-Unity#129]
Hello,

I have 2 questions :) Im not posting this as a bug or feature request because I imagine thats an issue with the REST service api.

1. Im trying to use FindLocations 3 overloads, setting (the default overload, the overload adding a point in new york, and the third adding a boundingbox in madrid - Spain) but it doesnt matter which overload I use, the returned results are allways the same. I am not sure if maybe I missunderstood how it was suppost to work.

2. I was digging in the REST service documentacion, and found this example in https://docs.microsoft.com/en-us/bingmaps/rest-services/locations/find-a-location-by-query 

"http://dev.virtualearth.net/REST/v1/Locations?culture=en-GB&query=Kings%20Road&o=xml&userLocation=51.504360719046616,-0.12600176611298197&o=xml&key=BingMapsKey"

the name in that example of the user location parameter is userLocation, while in the Unity sdk is just ul:

            url += $"&ul={  referenceLocation.LatitudeInDegrees.ToString(System.Globalization.CultureInfo.InvariantCulture)  },{ referenceLocation.LongitudeInDegrees.ToString(System.Globalization.CultureInfo.InvariantCulture) }";

is there any difference in using ul or userLocation?

here is the code I used for comparing results of the different overloads
`        
  
        var result2 = await MapLocationFinder.FindLocations(searchText);
        var result3 = await MapLocationFinder.FindLocations(searchText, new LatLon(40.6643, -73.9385));
        var result = await MapLocationFinder.FindLocations(searchText, new GeoBoundingBox(new LatLon(40.132691,-4.233586), new LatLon(40.682721, -4.090653)));
        
        string str = "";
        if (result.Locations.Count > 0)
        {
            for(int i = 0; i < result.Locations.Count && i < 3; i++)
            {
                str += result.Locations[i].DisplayName;
            }
        }
        Debug.Log(str);
        str = "";
        if (result3.Locations.Count > 0)
        {
            for (int i = 0; i < result3.Locations.Count && i < 3; i++)
            {
                str += result3.Locations[i].DisplayName;
            }
        }
        Debug.Log(str);

        str = "";
        if (result2.Locations.Count > 0)
        {
            for (int i = 0; i < result2.Locations.Count && i < 3; i++)
            {
                str += result2.Locations[i].DisplayName;
            }
        }
        Debug.Log(str);`

**Comment by kircher1** [comment]
The location and bounding box parameters are meant to improve the relevance of the results. I'm not entirely sure if in the bounding box case, the results are strictly filtered to that region though.

In terms of the `ul`/`umv` parameters, these are aliases for the longer parameter name. See here: https://docs.microsoft.com/en-us/bingmaps/rest-services/common-parameters-and-types/user-context-parameters

**Comment by Nalistic36** [comment]
Thanks for the response, I have done some tests and I confirm that the bounding box case results are not strictly filtered to the region. If one street name exists in 2 regions, it will return the street in the region inside the bounding box, but you will continue getting posible results if the name didnt match from other regions/countrys.

I missunderstood how the service worked, I was trying to implement a dropdown that tried to predict what the user was searching 

![Captura](https://user-images.githubusercontent.com/71155386/126614819-88341ccf-aeb1-42d0-bf15-28f7bfcfe60e.PNG)

But this will not work, the api will not try to predict what the user is trying to find, but try to find a location all arround the globe that could "fit" so even if the user types "gran v" (searching for gran via a big street in madrid) and the bounding box and position set both in madrid will not return the desired result.

Is it posible to accomplish something similar to what bings maps those in its web? I know POIS are not supported yet outside US, but a "try to predict" address

![Sin título](https://user-images.githubusercontent.com/71155386/126615368-8431ec51-4f31-4cee-9407-bde6ae9e60c5.png)

**Comment by Nalistic36** [comment]
I will answer myself in case any future readers are interested in this same topic.

there is indeed a REST service for archiving this, called autosuggest:

https://docs.microsoft.com/en-us/bingmaps/rest-services/autosuggest

**Comment by kircher1** [comment]
Yep, auto suggest is the way to go for that scenario. A feature request here would be to add a wrapper for autosuggest to the SDK.
