### ISSUE TITLE
Is it supports HDRP?

### ISSUE THREAD

**Issue by cauosg** [microsoft/MapsSDK-Unity#130]
Hello, we want to use this SDK with unity High Definition Render Pipeline.
When we changed default render pipeline to HDRP, map material seems not working. It shows elevations successfully, but map photo is not.
Please check HDRP is supported. thank you!

![image](https://user-images.githubusercontent.com/47723414/127076482-5eb2b2a4-e9b5-428f-aab6-ef12f08f9147.png)

**Comment by kircher1** [comment]
The shaders used to render the map are not HDRP compatible. Currently only the standard render pipeline and [URP](https://github.com/microsoft/MapsSDK-Unity/wiki/Universal-render-pipeline-support) are supported.

**Comment by cauosg** [comment]
Thanks for replying! Then, Is `MapsSDK-unity` supposed to support HDRP?

**Comment by kircher1** [comment]
Not currently. The custom shaders/materials of the SDK would need to be translated to HDRP.

The MapRenderer's default material could be overridden with a custom material, so if someone was able to create an HDRP compatible version of the current material and shader, then it is at least possible to swap out the current non-HDRP compatible material for one that works in HDRP. However, I'm not sure what the best path would be to translate a standard/URP shader to HDRP, so I don't have any guidance to share for how to go about that.
