### ISSUE TITLE
Bing Maps SDK Unity - adding game objects with long/lat - MapPinExample

### ISSUE THREAD

**Issue by shqipesalii** [microsoft/MapsSDK-Unity#132]
I have been testing the Maps SDK in Unity and I am referring to the Sample Project in Github : https://github.com/Microsoft/MapsSDK-Unity

When I run the MapPinExample project, I build and deploy it successfully, but then it does not run in Hololens 2. It just displays a black window with the title of the project. It is strange, because when I test MapServiceExample it works all fine.

What I want to do is display a map and then add game objects with a specific long/lat.

I would really appreciate your help.
I am looking forward to hearing from you.

**Comment by kircher1** [comment]
I've pushed a fix to the SampleProject to address this issue: b430726c415f5cabb4e29089f77266a7ae4d2948.
