### ISSUE TITLE
Map in World Scale. Unity 1unit = 1m

### ISSUE THREAD

**Issue by TheBriefTeam** [microsoft/MapsSDK-Unity#135]
Hey guys,

SDK looks great. I am currently developing an app for urban design. Basically a user selects a site on the map and starts drawing roads and buildings.
I have a question regarding scale. All generated roads and buildings are in 1unit = 1m scale. How to make actual map be the same scale as the geometry?
Also do you have a style builder like Mapbox on not yet?

I have a couple of screenshots.
1. User navigate the map as usual on the web
2. User draws site boundary ( so at this stage the boundary is a unity mesh which will to be drawn in 1unit = 1m scale)
3. User start drawing roads and buildings

Thank you
<img width="810" alt="Screenshot 2021-08-29 at 11 48 28" src="https://user-images.githubusercontent.com/15308495/131247776-ef7b64ab-1afe-4ed4-9fd0-82908430b064.png">
<img width="690" alt="Screenshot 2021-08-29 at 11 47 27" src="https://user-images.githubusercontent.com/15308495/131247779-9311b66e-6521-4697-8582-f0da4c3718d1.png">
<img width="651" alt="Screenshot 2021-08-29 at 11 47 16" src="https://user-images.githubusercontent.com/15308495/131247780-ef89317f-7ab5-40be-9421-f12c0cbefe81.png">

**Comment by kircher1** [comment]
The map itself will be 1x1m in Unity space assuming it's `GameObject`'s transform scale = 1... The dimensions of the map in Unity space can be controlled by adjusting the `MapDimensions`, but it is ultimately limited to 3x3m in Unity space.

The scale of content on the map is controlled by the `ZoomLevel`. 

![Alt Text](https://github.com/microsoft/MapsSDK-Unity/wiki/Content/FeatureGuides/MtFujiZoom.gif)

Note the dimensions of the map itself don't change as zoom level changes, but the scale of terrain does.

For adding objects to the map that have real-world dimensions, like buildings, as good starting point is using the `MapPin` system. The `MapPin` will be used to represent a building (or group of buildings), and those building meshes should be in real world meters. The `MapPin` will then handle both positioning the building based on a reference `LatLon` as well as scaling it to the right size relative to the map.

https://github.com/microsoft/MapsSDK-Unity/wiki/Attaching-GameObjects-to-the-map

For this use case, make sure the `MapPin` component has set [`UseRealWorldScale`](https://github.com/microsoft/MapsSDK-Unity/wiki/Microsoft.Maps.Unity#mappin) to true. Default is false.

**Comment by TheBriefTeam** [comment]
Hi there,

Thank you for your response. Yep, I saw this example.
The problem I have is at any given time I and generating procedural mesh (Game Objects) in the scene. These objects have to be in  1to 1 scale all the time.
I don’t want to scale objects with the map.

What if I want to measure area of the mesh face? With Pin scale it will give me wrong result.

How to determine when the map zoom level represents 1 to 1 scale ? This way I can zoom into specific area first and lock map zoom. And use my camera script to navigate in the scene.

Thank you,
Roman

**Comment by TheBriefTeam** [comment]
Hi there,

Thank you for your response. Yep, I saw this example.
The problem I have is at any given time I and generating procedural mesh (Game Objects) in the scene. These objects have to be in  1to 1 scale all the time.
I don’t want to scale objects with the map.

What if I want to measure area of the mesh face? With Pin scale it will give me wrong result.

How to determine when the map zoom level represents 1 to 1 scale ? This way I can zoom into specific area first and lock map zoom. And use my camera script to navigate in the scene.

Thank you,
Roman

**Comment by kircher1** [comment]
> What if I want to measure area of the mesh face? With Pin scale it will give me wrong result.

The MapPin GO's scale can be used to determine it's real-world scale.

> How to determine when the map zoom level represents 1 to 1 scale ? This way I can zoom into specific area first and lock map zoom. And use my camera script to navigate in the scene.

The map object is not intended to be rendered at 1:1 scale since it is constrained to 3x3m in Unity meters, which means only a 3x3 meter area would be visible at 1:1 scale and that is too small to be useful. Instead, to see a larger area, zoom level needs to be used.

To set the view of the map to a specific "area", if you have some notion of the geo bounding region for the area of interest, which could be defined either by 1) a LatLon center and a radius in real-world meters or 2) a LatLon bounding box, then this bounds could be used to adjust the map's center and zoom level properties to fit the area into the map view. I don't have the exact math required to do that at the moment, but it is possible.

**Comment by kircher1** [comment]
#124 has some sample code for setting the map view by a LatLon bounds.

**Comment by TheBriefTeam** [comment]
Thank you. Will give a go.
