### ISSUE TITLE
Alter 3D mesh region

### ISSUE THREAD

**Issue by TheBriefTeam** [microsoft/MapsSDK-Unity#136]
Is there a way to change the mesh of the 3D map?
Say I want a new building on the map, but it will overlap with existing map mesh.

**Comment by kircher1** [comment]
This has come up before but there's no solution for it currently. Most related is #1. Another option though is that disabling the 3D buildings entirely by setting `MapRenderer.MapTerrainType` to `ElevationOnly`, or `Flat` if you don't need elevation data either.
