### ISSUE TITLE
Override Alpha

### ISSUE THREAD

**Issue by mlathrop-bell** [microsoft/MapsSDK-Unity#137]
We often find that we are pulling map tiles from a 3rd party source and want to change the transparency of the layers. Is there a way to override (or perhaps multiply?) the alpha values by another value? I tied to look into the code, but I can't find the source for TileTextureLayer. Any ideas on how to accomplish this on a per HttpTextureTileLayer basis? We are hoping to avoid having to proxy the HTTP requests and rewrite the alpha values ourselves.

**Comment by kircher1** [comment]
There's probably a path to unblock this by using a custom shader, but I'll look into adding this functionality to the core SDK itself, e.g. an Opacity property on the TextureTileLayer.

**Comment by kircher1** [comment]
Added in 0.11.1
