### ISSUE TITLE
Getting Stared documentation: scopesRegistries url outdated/unavailable, manifest part misleading

### ISSUE THREAD

**Issue by MartinMajewski** [microsoft/MapsSDK-Unity#138]
**Describe the bug**
The `Getting Started` documentation is misleading and contains errors in 

[https://github.com/microsoft/MapsSDK-Unity/wiki/Getting-Started#option-2-start-from-scratch](https://github.com/microsoft/MapsSDK-Unity/wiki/Getting-Started#option-2-start-from-scratch)

~~The `scopedRegistries` URL seems to be outdated/unavailable.~~

Moreover, the manifest section should only contain copy and past-able code. The bracket in line 1 and the test `"existing dependencies"` is misleading.

Proposal: provide only text that can be copy and past and split the `copedRegistries` part and `dependencies` entry into separate chunks. Afterward, provide an inline example of how the manifest could look like. This is more user-friendly to read and understand.

**Comment by MartinMajewski** [comment]
The URL seems to work again. Maybe it was just a temporary issue.

However, current Unity versions have a form to insert a scoped registry:

![Screenshot 2021-09-09 at 21 52 39](https://user-images.githubusercontent.com/2221289/132753679-f17446bc-3fa9-4ba6-b024-6ac5919603de.png)

**Comment by kircher1** [comment]
Thanks, I updated the wiki to clarify existing dependencies shouldn't be removed. The new UI makes this simpler but I'm not sure it's available in all Unity versions.

**Comment by MartinMajewski** [comment]
The first mentioning of this menu option is made in version 2019.4

https://docs.unity3d.com/2019.4/Documentation/Manual/upm-scoped.html

MapsSDK starts from 2019.3, so maybe it is worth mentioning in the docs? I mean, 2019.4 is LTS!
