### ISSUE TITLE
Getting "Birds Eye" Altitude from Zoom Level/Zoom level from given Altitude

### ISSUE THREAD

**Issue by grantmorfitt** [microsoft/MapsSDK-Unity#141]
Hi there,

I'm attempting to set the zoom level of the map based on a value given for altitude for a flight sim type implementation. Is there any way to get this information? I can set the zoom level but the conversion from height AGL to this zoom is difficult to approximate. 

Thanks!

**Comment by AppleTesla** [comment]
I am curious about this as well. Any progress?

**Comment by kircher1** [comment]
My thought would be to set the zoom level so that the MapRenderer's dimension in real-world meters is some factor of the altitude.

```c#
var altitudeInMeters = 10000; // must be > 0 for following math to work.

var localMapDimension = Math.Max(mapRenderer.LocalMapDimension.x, mapRenderer.LocalMapDimension.y);
var altitudeToEarthCircumference = altitudeInMeters / Wgs84Datum.EquatorialCircumferenceInMeters;
mapRenderer.ZoomLevel = (float)Math.Log(localMapDimension , 2.0);
```

To account for Mercator distortion, scale altitudeInMeters by the inverse cosine of the map center's latitude.

**Comment by kircher1** [comment]
One more thought, for a more "bird's eye" view, you could try replacing the altitude with 2x the distance to the horizon. 

```c#
var distanceToOriginInMeters = altitudeInMeters + Wgs84Datum.MajorRadiusInMeters;
var approxDistanceToHorizonInMeters = Math.sqrt(Math.max(0.00001, distanceToOriginInMeters * distanceToOriginInMeters -  Wgs84Datum.MajorRadiusInMeters *  Wgs84Datum.MajorRadiusInMeters));
var valueToConvertToZoomLevel = 2.0 * approxDistanceToHorizonInMeters ;
```

Now the map would show (very roughly) the visible area to the horizon for a viewer at a given altitude... Like the last snippet, you'd probably want to scale the `valueToConvertToZoomLevel` by the 1.0/cosine of the map center's latitude.

Note, this code has not been tested :)
