### ISSUE TITLE
Update line positions based on maps center position

### ISSUE THREAD

**Issue by oneeypi** [microsoft/MapsSDK-Unity#143]
Hey,
i'd like to create a flight visualization with the MapsSDK. 
I use MapRenderers TransformLatLonAltToWorldPoint Method to generate the world positions of every point in my flights csv file.
Then I add the Values to Unitys LineRenderer positions. 

My Maps ZoomLevel is set to 14 for detail reasons of the ground.

When I start the animation of the plane i change the center position of the map to new planes position but the line stays on its initially added positions.
How can I update the Lines Position based on the new maps center position or is there any way you would recommend?

Thanks in advice!

This is my Animation Code. (markdowns code tags destroys the whole function - i'm sorry for that)

`
IEnumerator AnimatePlaneMovement()
{
    for (int i = 0; i < _lineCoordinates.Count - 1; i++)
    {
        while (_isPaused)
        {
            yield return null;
        }

        if (!_isPaused)
        {
            Vector3 nextPoint = _lineCoordinates[i + 1];
            Vector3 direction = (nextPoint - _plane.transform.position).normalized;
            Quaternion lookRotation = Quaternion.LookRotation(direction) * Quaternion.Euler(0, -90, 0);
            _plane.transform.rotation =
                Quaternion.Slerp(_plane.transform.rotation, lookRotation, 1.0f);
            _plane.transform.position = nextPoint;
            
            // Set new center Position of map
            var actualLocation = locationsInRealWorld[i];
            var centerCoordinates = new LatLon(actualLocation.LatitudeInDegrees, actualLocation.LongitudeInDegrees);
            _mapRenderer.Center = centerCoordinates;
            
            yield return new WaitForSeconds(0.10f);
        }
    }
}
`

**Comment by kircher1** [comment]
> How can I update the Lines Position based on the new maps center position or is there any way you would recommend?

Any time the map's Center or ZoomLevel changes, you'll need to retransform the line's LatLonAlt to world space. If you are animating center/zoom, this would require recomputing "LatLonAlt => world" every Update().
