### ISSUE TITLE
Show Entire Globe

### ISSUE THREAD

**Issue by AppleTesla** [microsoft/MapsSDK-Unity#147]
Hi there,

Is it possible to render a much larger view of the Earth, preferably the entire globe?

Use Case: I would like to plug in a lat, long and elevation to then have the map render that precise location as if I were in a plane at that elevation. I'm trying to build a flight simulator.

Awesome work Microsoft!
Jaron

**Comment by bjudson22** [comment]
Couldn't you just set the zoom level to max on the Maprenderer? This gives you an entire view of the Earth. You could then place a MapPin component on your gameobject which details latitude, longitude and elevation. 

However, if you're trying to make the Earth into a literal sphere, I think Bing removed that feature. 

I hope this helps.

**Comment by kircher1** [comment]
The SDK provides a "tabletop" map for MR scenarios. The flight-sim immersive view is not possible with this visualization.

The zoom level of course can be used to render the map at different scales, and if you want to visualize the location of a plane over the map, you could look into the MapPin system. First-person/immersive views from the plane though aren't possible.
