### ISSUE TITLE
Variant for TTRPGs?

### ISSUE THREAD

**Issue by LordRelentless** [microsoft/MapsSDK-Unity#148]
Is it possible to create a standalone version of this SDK which allows for drag and drop placement of map tiles or assets for a beginner that doesn't require VR? A map tool like this would be very useful for creating TTRPG maps for games like D&D, D20 Modern, Starfinder, and Warhammer 40k. A version of this that someone like me (with really no coding experience) can either autogenerate a map with selected terrain features or drag and drop visual elements to an empty map to build custom cities, terrain, etc, would be an awesome reimagining of your project and I suspect many TTRPG players would find it very useful.

**Comment by kircher1** [comment]
While the default mode of the map is certainly representing the real-world data, there are various ways to input custom data (like elevations and textures) to describe the map surface, so it is certainly possible to create an unrealistic map surface.

There may be some more specific things that would be useful from the level-building point of view. One feature like this in the Maps SDK now is that ctrl-right clicking the map in the editor creates a MapPin GameObject at that location on the map.
