### ISSUE TITLE
Latest Unity 2019.4.32f1 UWP Build

### ISSUE THREAD

**Issue by TerraSame** [microsoft/MapsSDK-Unity#149]
**Describe the bug**
             Hello... I have been attempting to rebuild a previous project but from scratch and updating to your latest
          2019.4.32f1 files. 
             I am not able to compile to the UWP platform as  "BuildType"- "Executable Only"...  
          I have tried many compiles with many potential variable selection changes. As well, I have researches the 
          internet looking to find the problem and tried many possable suggestions. But, all to no avail... 
            I have spent 3 straight days fighting this so now I ask for assistance. I have many proper running projects
         from the Unity 2019.2.19f1 original package.
            The project runs well in the Unity editor but when I compile i always get this error
            IOException: Failed to copy Packages/com.microsoft.maps.unity/Plugins/CompressionNative/iOS/MicrosoftGeospatialDecompressionStubs.cpp to Temp\StagingArea\Data\il2cppOutput\MicrosoftGeospatialDecompressionStubs.cpp: The system cannot find the path specified.

Utility.ThrowWin32IOException (System.Int32 errorCode, System.String message) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/Utility.cs:596)
Utility.CopyFile (System.String sourceFile, System.String destinationFile) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/Utility.cs:624)
PostProcessWinRT.CopyCppPlugins (System.String cppOutputDir, System.Collections.Generic.IEnumerable`1[T] cppPlugins) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:2024)
PostProcessWinRT.<RunIL2CPPForExecutableBuild>b__113_0 (System.String cppOutputDir) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:1979)
UnityEditorInternal.IL2CPPBuilder.Run () (at <4330b7b9ef6d4dd780b09ebcbf09fc68>:0)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at <4330b7b9ef6d4dd780b09ebcbf09fc68>:0)
PostProcessWinRT.RunIL2CPPForExecutableBuild () (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:1979)
PostProcessWinRT.RunIL2CPP () (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:1904)
PostProcessWinRT.Process () (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:217)
UnityEditor.UWP.BuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:85)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.UWP.BuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:89)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <4330b7b9ef6d4dd780b09ebcbf09fc68>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <4330b7b9ef6d4dd780b09ebcbf09fc68>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
         
         
          
**To Reproduce**
1. Please see attached jpeg file for settings etc...
then compile for "Build Type Executable Only" as can be see in attached pic...
My drives have plenty of space so that as others have suggested, is not the problem...
I assume that I have not setup something properly but it all worked properly with your earlier version and I have matched all settings.
2. Is this is a bug that I have found you will find out upon compiling.
   Otherwise, please let me know what I am doing wrong...
3. In the mean time, I will continue my efforts and try to surmount this issue.
4. Thanks for your efforts :)

**Expected behavior**
Hopefully find either the bug or direct me as to my fault...
**Screenshots**
Please see attached...
**Environment (please complete the following information):**
 - Unity version: [e.g. 2019.4.32f1]
 - Maps SDK Package version: [e.g. 0.11.0]

Thanks!
and info, please write to paul@terrasame.com
If I find the problem, I will update this post...
Thanks Brian & team!
Paul

**Comment by kircher1** [comment]
I can repro this too. Note. the "D3D Project" option (instead of "Executable Only") does build successfully. If you can use that instead, it should unblock the build. 

In either case, this seems like a bug/inconsistency in Unity. I'll look into creating a minimal repro sample.

**Comment by TerraSame** [comment]
Hello Brian...
As usual, with in the next 12 hours after posting on your forum with a
problem, I found that if I build for PC as your Sample project is set up,
it does compile and fire up through Steam/WMR... So, I do now have this
working as this seems to be set up for XR/VR compiles...
Thanks so much for all your efforts!
Paul

**Comment by kircher1** [comment]
Here is the Unity issue tracker for this bug: https://issuetracker.unity3d.com/issues/uwp-executable-only-build-fails-when-package-includes-native-code-file
