### ISSUE TITLE
Terrain collider

### ISSUE THREAD

**Issue by galdalali** [microsoft/MapsSDK-Unity#150]
**Is your feature request related to a problem? Please describe.**
We're looking for an accurate terrain collider.

**Describe the solution you'd like**
Put simply, we want to know when a game object intersects with the map

**Comment by kircher1** [comment]
Since the map is dynamically loading data at various LODs, colliders are not provided. The Raycast API of MapRenderer can be used to detect where a ray intersects the surface, but more complex intersections (sphere/mesh) are not supported.
