### ISSUE TITLE
Adding a child MapPin to the MapRenderer - LOD Possable?

### ISSUE THREAD

**Issue by TerraSame** [microsoft/MapsSDK-Unity#151]
Hello...
I have managed to figure out how to use a Sprite with a Video Player attached as a map pin and I have numorous videos that play when using the tour example and with a revised list of stopping locations of an entire state. The problem is that I have not yet figured out how to have only one video play at a time. I tried adding the LOD system so the videos only show up upon getting close enough to fade in the sprite/video. I imagine you can visualize how much a location based video can enhance the tour system... 
The Unity Standard LOD system seems to not function used on the map pins.
So, the question is: 
Might there be a way to accomplish only showing map pins by distance?
Thanks

(Edit) 
Also, I have noticed that the Map Pin Cluster system does have a sort of LOD system built in so I have experimented with that system. The simple Map Pin system is much easier so all I really need is an on/off mechanisim set by a simple distance, editable for each individual Video/Map Pin. At present each Video Map Pin does turn off when, from the tour zooming, the Video Map Pin leaves the map extents.
Any advice or assistance on this matter is greatly appeciated.
Thanks Brian
Paul

(Edit 2) 
Hey...
So, today I tried using a 360 video as a Map Pin using AVPro Video asset.
The system works and would be dam cool but I have the same issue where I am not able to, using the "Video Trigger" script from AVPro to start & stop the video upon entering and exiting the sphere will not work as it seems that any children of the main Map Pin child of the Map does not activate.... Therefore, as already mentioned, any assistanse or advice will be greatly appreciated.
Thanks

**Comment by kircher1** [comment]
If you can structure the MapPin GameObject heirarchy like this:
 * Root GO => contains MapPin
     * Child GO => Contains LOD System 
         * ... Video GO

Then the Root GO will be disabled whenever it is off the map (this is automatically handled by the MapPin), and then the LOD system can be used to disable the child video whenever it is too far away. Alternatively, instead of LOD system, you could do some custom logic for enabling/disabling video based on distance to camera or some other constraint.
