### ISSUE TITLE
Assets\Microsoft.Maps.Unity.Examples\HudExample\Scripts\AnimateToLocation.cs(20,15): error CS0246: The type or namespace name 'Vector2D' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by S601327412** [microsoft/MapsSDK-Unity#159]
**Describe the bug**
The type or namespace name 'Vector2D' could not be found (are you missing a using directive or an assembly reference?) in scripts under；

**To Reproduce**
open this repo ues Unity 2019.4.13f1c1

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Unity version: [e.g. 2019.4.1f1]
 - Maps SDK Package version: [e.g. 0.11.1]

in Console some error like this
Assets\Microsoft.Maps.Unity.Examples\HudExample\Scripts\AnimateToLocation.cs(20,15): error CS0246: The type or namespace name 'Vector2D' could not be found (are you missing a using directive or an assembly reference?)
Assets\Microsoft.Maps.Unity.Examples\Common\Scripts\MapInteractionHandler.cs(24,13): error CS0246: The type or namespace name 'Vector2D' could not be found (are you missing a using directive or an assembly reference?)
Assets\Microsoft.Maps.Unity.Examples\Common\Scripts\MapInteractionHandler.cs(28,13): error CS0246: The type or namespace name 'Vector2D' could not be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\MapControls.cs(24,13): error CS0246: The type or namespace name 'Vector2D' could not be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\MapControls.cs(28,13): error CS0246: The type or namespace name 'Vector2D' could not be found (are you missing a using directive or an assembly reference?)

![mapissue](https://user-images.githubusercontent.com/37855775/150909827-83ae95f1-eba2-4cab-92ab-a37787aaed99.png)

**Comment by kircher1** [comment]
Vector2D has been replaced with [Microsoft.Geospatial.MercatorCoordinate](https://github.com/microsoft/MapsSDK-Unity/wiki/Microsoft.Geospatial#mercatorcoordinate).
