### ISSUE TITLE
display a gameobject on the map that represents the gps data of the user

### ISSUE THREAD

**Issue by costarita** [microsoft/MapsSDK-Unity#160]
how do i get the gps data displayed on the map? i m trying it with the following script but i dont have acess to the latlon values in the mappin script.... please help

**Comment by costarita** [comment]
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.Android;
using UnityEngine;
using System.Collections;
using Microsoft.Geospatial;
using Microsoft.Maps.Unity;

public class GPS : MonoBehaviour
{
    public Text gpsOut;
    public bool isUpdating;
    private double latitude;
    private double longtitude;
    private void Update()
    {
        if (!isUpdating)
        {
            StartCoroutine(GetLocation());
            isUpdating = !isUpdating;
        }
       
        Debug.Log(longtitude + " " +  latitude);
        LatLonWrapper position = new LatLonWrapper();
        position.Latitude = latitude;
        position.Longitude = longtitude;
        pin._location = longtitude + " " + latitude);
        pin.Location = position.ToLatLon();


        decalRightSidePos.GetComponent<Decal>().Sprite = decalprefab[index];


    }

    IEnumerator GetLocation()
    {

        if (!Permission.HasUserAuthorizedPermission(Permission.FineLocation))
        {
            Permission.RequestUserPermission(Permission.FineLocation);
            Permission.RequestUserPermission(Permission.CoarseLocation);
        }



        // Check if the user has location service enabled.
        if (!Input.location.isEnabledByUser)
            yield return new WaitForSeconds(5);

        // Starts the location service.
        Input.location.Start();

        // Waits until the location service initializes
        int maxWait = 20;
        while (Input.location.status == LocationServiceStatus.Initializing && maxWait > 0)
        {
            yield return new WaitForSeconds(1);
            maxWait--;
        }

        // If the service didn't initialize in 20 seconds this cancels location service use.
        if (maxWait < 1)
        {
            gpsOut.text = "Timed out";
            print("Timed out");
            yield break;
        }

        // If the connection failed this cancels location service use.
        if (Input.location.status == LocationServiceStatus.Failed)
        {
            gpsOut.text = "Unable to determine device location";
            print("Unable to determine device location");
            yield break;
        }
        else
        {
            gpsOut.text = "Location" + Input.location.lastData.latitude + " " + Input.location.lastData.longitude;
            // If the connection succeeded, this retrieves the device's current location and displays it in the Console window.
            print("Location: " + Input.location.lastData.latitude + " " + Input.location.lastData.longitude + " " + Input.location.lastData.altitude + " " + Input.location.lastData.horizontalAccuracy + " " + Input.location.lastData.timestamp);
            latitude = Input.location.lastData.latitude;
            longtitude = Input.location.lastData.longitude;

        }


        // Stops the location service if there is no need to query location updates continuously.
        isUpdating = !isUpdating;
        Input.location.Stop();
    }
}

**Comment by kircher1** [comment]
To place an object on the map at the current GPS location, take a look at using a [MapPin](https://github.com/microsoft/MapsSDK-Unity/wiki/Attaching-GameObjects-to-the-map) for that, e.g., you can `FindObjectType<MapRenderer>()`, and create ad add a `MapPin` to the `MapRenderer`. When GPS location changes, update the pin's `Location` property to match that latest reading.

If you are having issues getting the GPS location itself, the device you're running on will need to have GPS support and then also the location capability will need to be enabled for  the app. On Android for instance, Unity should be adding the correct permissions automatically when using the Location service. (See docs [here](https://docs.unity3d.com/Manual/android-permissions-in-unity.html#unity-handled-permissions)). But, for iOS or other OS's, you may need to ensure the relevation location/permission capability is set in the Player Settings.

There's a new sample scene in the demo project for the SDK that shows how to use Location service. See here: https://github.com/microsoft/MapsSDK-Unity/tree/master/SampleProject/Assets/Microsoft.Maps.Unity.Examples/CurrentLocationExample
