### ISSUE TITLE
Hide MapIcon

### ISSUE THREAD

**Issue by minimalisticMe** [microsoft/MapsSDK-Unity#161]
Hi,

is it possible to hide/disable the blue transparent icon `MapsSDK-EditorIcon.png` from path `[...]\Editor\Resources\MapsSDK-EditorIcon.png`?
It shows up on Script and Play mode, see images below:
![grafik](https://user-images.githubusercontent.com/13404680/151432395-1b576ec8-8e19-4ccd-8412-e950de5d16f6.png)
![grafik](https://user-images.githubusercontent.com/13404680/151432428-1e65d6f4-c44f-4f6b-9b43-6a13d7a8d434.png)

**Comment by kircher1** [comment]
The visible icons in the scene view are controlled by the Unity Editor settings. I believe it's in the "Gizmos" dropdown. See here: https://docs.unity3d.com/2022.2/Documentation/Manual/GizmosMenu.html?msclkid=0c92e944baa011ecbe9414f6673b35db

**Comment by minimalisticMe** [comment]
@kircher1 You are correct, unselecting these two options solved my issue:
![grafik](https://user-images.githubusercontent.com/13404680/168824391-8a3891a9-b8dd-4a51-86cc-0f3c17c4a4d7.png)

Thank you very much!
