### ISSUE TITLE
Update Docs for MapPin Clustering

### ISSUE THREAD

**Issue by cshieldsboss** [microsoft/MapsSDK-Unity#163]
Hey there! 

After a couple days of debugging we finally figured out that the map pin clusters "Clustering Threshold" is hard coded with a minimum of 2. We never saw in the documentation on how this threshold works but discovered that it creates a cluster once 3 pins are close to each other, not 2. We found a work around to make what we needed work but would suggest updating the documentation with a bit more info and/or making that threshold have a minimum of 1 so you can have a cluster pin created from just 2 pins close to each other.

Thanks!

**Comment by kircher1** [comment]
This sounds more like an off by one bug in the SDK. It would make sense to support 2-pin clusters. Once the map's zoom level reaches a certain threshold (level 17, I believe), all the pins would be de-clustered anyways.

**Comment by kircher1** [comment]
Fixed in 0.11.2
