### ISSUE TITLE
External API Key

### ISSUE THREAD

**Issue by kpprt** [microsoft/MapsSDK-Unity#164]
Hi,

The API Key is currently serialized and stored as plain text directly in either a scene or a prefab. In a public project, that would expose the key. But even in private projects that can be a security issue.

So my question is: is it possible to load the API Key from a separate file (that could be ignored in version control) or environment variable? Or is there any other way?

Thanks,
Chris

**Comment by kpprt** [comment]
Try this search for example:
https://github.com/search?l=Unity3D+Asset&q=_developerkey&type=Code

**Comment by kircher1** [comment]
The key can be programmatically set during play mode, see the [DeveloperKey](https://github.com/microsoft/MapsSDK-Unity/wiki/Microsoft.Maps.Unity#mapsession) property on MapSession. By using that API in play mode, the key could be stored and read from elsewhere without saving it to the scene.

Another thing that could be useful, depending on the use case, is adding an IP Range filter to a specific key. More info [here](https://blogs.bing.com/maps/2018-05/Announcing-Enhanced-Security-for-Bing-Maps-API-Keys?msclkid=d5e7e529ba9d11ec8f7589d3db7e3238).

**Comment by kpprt** [comment]
Thank you for your reply! Setting the DeveloperKey during play mode might help a little, but it will not solve the problem for using the map in the Editor. You would need to put in the credentials again in the serialized field in order for the map to work in the Editor.

That's why I still think it would be better to implement the external loading right in the SDK. Or am I missing something here?

**Comment by kircher1** [comment]
To make that work in edit mode too, the script that sets the key programmatically could use other Unity callbacks, like OnBeforeSerialize or callbacks from AssetModificationProcessor, and use these to empty the key out of the MapSession before it's serialized... Also, there's always options outside of Unity APIs, like tracking scene file changes with the .NET FileSystemWatcher.

For the SDK itself, there will likely be additional options to load the key from a different source in a future release, but that's a work in progress.

**Comment by kpprt** [comment]
Okay, thanks for the feedback! I will look into it and see if that works out. 👍

**Comment by kircher1** [comment]
In 0.11.2 there's a couple more options for supplying  the dev key; One is using a Resource file, which can be gitignored, or specifying that the key will be provided externally. Check the updated [Getting Started](https://github.com/microsoft/MapsSDK-Unity/wiki/Getting-Started#5-provide-a-bing-maps-develper-key) docs.
