### ISSUE TITLE
Request a feature for lookup location (lat,lon) info which returns the city/town name from the map label layer

### ISSUE THREAD

**Issue by jimmy12day** [microsoft/MapsSDK-Unity#17]
**Is your feature request related to a problem? Please describe.**
Current map label layer is passing a MapLabel object which only include the Text and Style but not the lat lon of this.
**Describe the solution you'd like**
Option one, create a lookup function in the maplabel layer which take lat lon as input and return the city and town name for it.Those info should be read only.
**Describe alternatives you've considered**
Option two, pass the lat lon info to the MapLabel and organize the maplabels as State/City/Town which allow people to get all the information.  Those should be  readonly.
**Additional context**

**Comment by kircher1** [comment]
Hi, thanks for the feature request!

To clarify, do you need the actual LatLon of the label itself, or just a way to look up labels on the MapLabelLayer which may be "near" a LatLon?

**Comment by jimmy12day** [comment]
Hi Kircher1,
Thank you for the reply. I am looking for an actual Latlon of the label itself. If that is impossible, can we make the label in a well know hierarchy? For example, the 'Country' name should be the parent of the 'State' name, The 'State' name should be parent of the 'City' name, the 'City' name should be the parent of all the town name. The later option will be ideal. 
Bin

**Comment by jimmy12day** [comment]
I figured a solution for now. The scale of the maplabels are different and seems to be linear. So the largest map label can be identified.
