### ISSUE TITLE
About using -batmode

### ISSUE THREAD

**Issue by yuki3358** [microsoft/MapsSDK-Unity#172]
Right now I'm trying to create a batch snapshot of a map using the Map SDK, but when I try to generate the map in -batch mode it doesn't, but there are some precautions on the Map SDK side. mosquito?

**Comment by kircher1** [comment]
If you're trying to take a screenshot of a scene with a map, try using the Recorder package: https://docs.unity3d.com/Packages/com.unity.recorder@2.5/manual/index.html

This is what was used for capturing the screenshots/gifs you see in the Readme and wiki.
