### ISSUE TITLE
3D polygon buildings.

### ISSUE THREAD

**Issue by AlexAndSomethingElse** [microsoft/MapsSDK-Unity#178]
Hello!
How to change the map settings so that the buildings are 3D rendered in height, as in the first picture?
I only have a completely flat map (second picture).

![3D](https://user-images.githubusercontent.com/108466559/176667202-fb865b22-c2cc-4c21-be75-3a9bf56d9613.png)

![flat](https://user-images.githubusercontent.com/108466559/176667232-69702735-03bb-4414-a840-2d2468c1fa06.png)

**Comment by AlexAndSomethingElse** [comment]
Current settings.

![image](https://user-images.githubusercontent.com/108466559/176672252-a090ed6b-d72b-4af4-9be2-8c1197030d06.png)
![image](https://user-images.githubusercontent.com/108466559/176672410-53c41cae-01ed-4b01-8641-faef0eb48e2e.png)
![image](https://user-images.githubusercontent.com/108466559/176672525-32673a75-218d-4519-99f6-7564223c7f67.png)

**Comment by cafigz** [comment]
There is an example called Map Services Example that has a 3D example of a building.
Give it a look, it might have what you need.

https://github.com/microsoft/MapsSDK-Unity/tree/master/SampleProject/Assets/Microsoft.Maps.Unity.Examples/MapServicesExample

![image](https://user-images.githubusercontent.com/103571527/179036731-0e51ccf0-6e53-4f02-bca1-6e9403390d99.png)

**Comment by kircher1** [comment]
The extruded style symbolic building shown in the original issue are not supported by this SDK. I'd file this more generally under supporting other vector data sources (#30).
