### ISSUE TITLE
Getting LatLon when clicking on map

### ISSUE THREAD

**Issue by cafigz** [microsoft/MapsSDK-Unity#181]
Hi!
I managed to get the Latitude and Longitude of the point where my RayCast hits, but now I want it to only trigger when I'm either pressing on the map (near interaction) or clicking on it with the air tap.
At the moment this is my code:
![image](https://user-images.githubusercontent.com/103571527/179638826-095c75cd-dfe5-4598-972a-380111f2a33d.png)

My question is:
How to I change the if to only trigger when I air tap or use the near interaction?

Best regards

**Comment by kircher1** [comment]
Take a look at how the MixedRealityMapInteractionHandler component is used in the sample project. There should be an event to hook into for getting clicks on the map.

If it doesn't exactly do what you need, the implementation of that class should be a helpful reference: https://github.com/microsoft/MapsSDK-Unity/blob/master/SampleProject/Assets/Microsoft.Maps.Unity.Examples/Common/Scripts/MixedRealityMapInteractionHandler.cs
