### ISSUE TITLE
Will the project support MRTK3 and Unity XR interaction Toolkit? 

### ISSUE THREAD

**Issue by theBHawk** [microsoft/MapsSDK-Unity#184]

**Comment by kircher1** [comment]
The sample project provides some helper scripts and examples for using the map with MRTK(v2). I do not know for sure if these helper scripts are upgradable to the new MRTKv3 specifically.

In general though, the map SDK won't have any direct dependencies on MRTK or XRTK. It's parallel to these sorts of toolkits.
