### ISSUE TITLE
Opening Port To Incoming UDP traffic

### ISSUE THREAD

**Issue by cafigz** [microsoft/MapsSDK-Unity#188]
Hi! I was setting up a project using MRTK, and I managed to set up a server (hosted by my desktop) and connect my Hololens 2 to it. At the moment I can send traffic to said server, but I cannot receive any information sent by the server.
I believe I have to add a rule to the Hololens firewall, but I didn't manage to find anything in the Settings. Is it in the Device Portal? How should I open the 7777 port in my hololens to incoming UDP traffic?

Best regards

**Comment by kircher1** [comment]
It does seem like something that could be managed by the device portal, but not sure. This question is better to ask in a different forum.
