### ISSUE TITLE
Will MapsSDK-Unity run fine on Unity 2021.3 LTS?

### ISSUE THREAD

**Issue by HiroOfHyrule** [microsoft/MapsSDK-Unity#189]
Hello,
So according to the Unity Support Matrix in the documentation, it only says that up to Unity 2020.3 LTS is supported and there is no listing for Unity 2021.3 LTS. I'm unsure if this matrix is simply outdated or if Unity 2021.3 LTS is missing because it is unfortunately not supported, so I wanted to get confirmation whether or not MapsSDK-Unity is known to be able to be used in Unity 2021.3 LTS without significant issues. 
Thank you

**Comment by xFrost64** [comment]
Hello,
In my project the map works fine without 3D on. But when 3D is turned on and the map is zoomed in close enough to get the 3D data to populate, it sometimes throws "System.ArgumentNullException: Buffer cannot be null. Parameter name: buffer". Once this error happens the map tiles will no longer update as the map moves around.

I posted the error in my log below, hope this helps!

[MapErrorLog.txt](https://github.com/microsoft/MapsSDK-Unity/files/9922052/MapErrorLog.txt)

**Comment by kircher1** [comment]
I haven't seen that issue. Is it 2021 specific? In general, Unity 2021 should work. Unity 2022 or possible 2023, I'm not sure about.
