### ISSUE TITLE
Map Session failing during initialization will never try to restore itself automatically

### ISSUE THREAD

**Issue by Kiwithepaladin** [microsoft/MapsSDK-Unity#190]
**Describe the bug**
MapSession wont **ever** _attempt_ to re-initialize itself.
In essence, if your initialization yields an a network error, You will need to "manualy" resolve it (I.E: reloading the scene)

**To Reproduce**
	- Disable Internet connection.
	- Run a scene with Map Renderer and Map Session attached to an object.
	- Get **Error 1** (See attached screenshot).
	- Enable Internet connection.
	- MapSession wont load tiles due to poor initialization.
	
**Expected behavior**
	I would **Expect** one of few things to happen:
		- Whenever Internet connection is being restored MapSession will _attempt_ to re-initialize itself.
		- Disabling the object which MapSession is attached to (or the script itself) will force an _attempted_ re-initializion.
		- Have an accessible reconnection method.
		- Publicly accessible event that you can hook to whenever connection is lost and or restored.
			
**Screenshots**
![Screenshot_20221205_155020](https://user-images.githubusercontent.com/24848940/205653942-1ce1acd6-125c-4df9-835e-904229814f37.png)

**Environment:**
 - Unity version: [2021.3.12f1]
 - Maps SDK Package version: [0.11.1]

**Additional context**
Marked as bug report however can be also considered a feature request, not enirelty sure if current behaviour is by design.

**Comment by kircher1** [comment]
Right, if the map starts offline, there's no automatic connection retry. Unless you are using custom data purely offline, the device needs an active internet connection.

To immediately work around this, you may try hooking into Unity's log events and when intercepting a message like this, you could tear down the MapSession and try and recreate it at some point in the future? Sort of a DIY retry.  I think this is the Unity log callback: https://docs.unity3d.com/ScriptReference/Application-logMessageReceived.html
