### ISSUE TITLE
Elevation Offseting

### ISSUE THREAD

**Issue by PetrTech** [microsoft/MapsSDK-Unity#192]
Hi, we are currently trying to implement MapsSDK in our game but we ran into a problem. Whenever we would load few new chunks the map elevation will offset/adjust itself. Is it possible to turn this off or alteast make it not be visible? If so, how? Thanks for any kind of help. I've attached a video that showcases what we're trying to disable.

https://user-images.githubusercontent.com/55279432/211211967-a310394d-ce72-452b-8bf5-fd9bef402361.mp4
(It's that subtle movement up and down when I move the terrain)

**Comment by kircher1** [comment]
I believe the behavior can be overridden by setting `MapRenderer.ElevationBaselineOverride` to a value that works for your scene.

**Comment by PetrTech** [comment]
Yes, it indeed works, thanks!
