### ISSUE TITLE
3d gameobject on bing map in unity

### ISSUE THREAD

**Issue by nctran108** [microsoft/MapsSDK-Unity#195]
Hi,
now I am using hololen2 to create an human interface which has Bing map sdk as a base and a 3d game object on the top of the map. But I want the game object display in correct coordinate or location. But I don't know how to get latitude and longitude from Bing map. I also want to move the game object base on new longitude and latitude. 
can you give me some example how to do it? 
<img width="549" alt="Screenshot 2023-02-10 114852" src="https://user-images.githubusercontent.com/60759653/218148762-22083481-2e02-40f6-983e-3ccca454d68f.png">

**Comment by kircher1** [comment]
I think these are the relevant docs: [Animating the map](https://github.com/microsoft/MapsSDK-Unity/wiki/Animating-with-MapScenes)
 [Raycasting the map](https://github.com/microsoft/MapsSDK-Unity/wiki/Raycasting-the-map)
