### ISSUE TITLE
Increasing the LocalMapDimension tile size to above 3x3

### ISSUE THREAD

**Issue by joshkbaker** [microsoft/MapsSDK-Unity#197]
Is there anyway I can increase the tile size by more than 3x3.

This for a golf AR app and quite often even at a higher zoom level, I can't see the entire length of the hole.

Seems odd that it's locked, especially when I can use multiple MapRenderers to render two different areas. 

Thanks

**Comment by galdalali** [comment]
Already opened - [Immersive mode #2](https://github.com/microsoft/MapsSDK-Unity/issues/2)
Joining the request
