### ISSUE TITLE
Immersive mode

### ISSUE THREAD

**Issue by kircher1** [microsoft/MapsSDK-Unity#2]
**Is your feature request related to a problem? Please describe.**
The current map is limited to a table-top sized view. Some scenarios require a view where one can see much more map area, possibly to the horizon. 

**Describe the solution you'd like**
This solution would involve providing a mode that can be toggled on the MapRenderer, for either immersive mode or table-top mode. Table-top mode would continue to allow for configuring the dimension and color of the clipping sides. Immersive mode would essentially disable these restrictions and allow rendering the map to the horizon. Map data would fall off in quality, as is typical for most LOD based systems, to maintain a pixel-to-texel ratio.

**Comment by diogo-garcia** [comment]
No updates on this matter since 2019? =\
