### ISSUE TITLE
MRTK3 Pointer Handlers

### ISSUE THREAD

**Issue by xiiihopeestheim** [microsoft/MapsSDK-Unity#205]
Looks to me that the interfaces:
IMixedRealityPointerHandler, IMixedRealityInputHandler<Vector2>, IMixedRealityFocusHandler, IMixedRealityRaycastProvider
are now obsolete in MRTK3, and MapRayCastProvider.cs and MixedRealityMapInteractionHandler.cs needs to be rewriten 😅

Does anyone have good samples on allowing panning the Map Renderer using MRTK3 pointer handlers? Thanks!

**Comment by briotto-deloitte** [comment]
Hi @xiiihopeestheim, did you have any luck getting panning to work on MRTK3?
