### ISSUE TITLE
bing maps not working properly unity in WebGL export

### ISSUE THREAD

**Issue by pawantha** [microsoft/MapsSDK-Unity#212]
**Describe the bug**
bing maps not working properly unity in WebGL export

**Expected behavior**
it seems like the map object is being displayed, but the map itself is not loading. this is and basic scene with no code. the only thing I added is the camera movement code. others are default settings in Unity.

![Screenshot 2024-01-10 140115](https://github.com/microsoft/MapsSDK-Unity/assets/53902756/e7c6fa51-4f1a-4dea-80a5-39d63cc0f332)

**Environment (unity WebGL):**
 - Unity version: [2023.01.20f1]
 - Maps SDK Package version: [0.11.2]

**Comment by kircher1** [comment]
This is expected, WebGL is not supported
