### ISSUE TITLE
Map Location is Flat and not 3D

### ISSUE THREAD

**Issue by sarmiese** [microsoft/MapsSDK-Unity#22]
Hey, I have a question regarding some of the locations found in the map. This is perfect for what I need but I need to be able to zoom into Dallas, Texas. but for some reason when I zoom in there is no height to the city, its just flat and I am under 'Default' map type.

One of the 'seams' of where the map stops being 3D is in (32.74, -97.181)
The city of Dallas is around (32.778, -96.8036)
I am using Unity 2018.3.14 and also tried several other higher up versions. I downloaded the 'Microsoft.Maps.Unity-Core-0.3.0.unitypackage' from the Releases page as I don't need to incorporate Hololens into my project. 

I am just wondering if this is normal or is there is something im not doing right to get the Dallas City to show in 3D - or if there is anything I can do to get this working, Please and thanks!

**Comment by kircher1** [comment]
I cross checked the map data coverage and Dallas is an area that is _not_ covered by the higher resolution 3D data. Fort Worth however is covered and the lat-lon is on the edge of the Fort Worth coverage . In areas without the higher resolution data, the map falls back to a lower resolution elevation model, which in the Dallas area is generally flat.

Sorry to report there is no coverage in Dallas! Another way to see what areas will be covered by higher resolution 3D data is to check the Windows Maps app. In the menu ('...') of that app, there is an "Explore 3D Cities" option which enumerates the areas that have 3D coverage.
