### ISSUE TITLE
Transit view

### ISSUE THREAD

**Issue by shyam-tilt** [microsoft/MapsSDK-Unity#26]
Does the sdk support transit view?

**Comment by kircher1** [comment]
Unfortunately not, the SDK doesn't support any transit information or route overlays.

Depending on exactly what you are looking for, one avenue may be to find a tile-based image service that provides a transit map, and then you may be able to use the new [TextureTileLayer](https://github.com/microsoft/MapsSDK-Unity/wiki/Microsoft.Maps.Unity#texturetilelayer) to overlay that on top of the MapRenderer.
