### ISSUE TITLE
Geospatial services

### ISSUE THREAD

**Issue by kircher1** [microsoft/MapsSDK-Unity#3]
Expand the Maps SDK to support headless APIs, i.e. APIs that don't depend directly on the MapRenderer, to do things like geo-coding, reverse geo-coding, or route finding. This would basically provide a Unity-compatible interface over some of the existing Bing Maps APIs, but would use the managed Geospatial types to inter-op easily with the existing classes in the Maps SDK.

**Comment by jimmy12day** [comment]
Any progress on it?

**Comment by kircher1** [comment]
Quick update:
* The sample project now has a [MapServicesExample](https://github.com/microsoft/MapsSDK-Unity/wiki/Sample-project#mapserviceexamplescene) scene that uses the MapLocationFunder API.
* API docs have been added to the [wiki](https://github.com/microsoft/MapsSDK-Unity/wiki/Microsoft.Maps.Unity.Search). 
* The source code for the map services has been committed to the supporting scripts [here](https://github.com/microsoft/MapsSDK-Unity/tree/master/SupportingScripts/Scripts/MapServices).
