### ISSUE TITLE
Zoom Level To/From Altitude Conversions

### ISSUE THREAD

**Issue by keenanwoodall** [microsoft/MapsSDK-Unity#33]
Is there a utility method for converting to and from zoom levels and altitudes? I need to sync a camera that orbits a globe with a Map Renderer.

**Comment by kircher1** [comment]
One potential way of doing this is adding a MapPin component to your Camera's GameObject and making that GameObject a child of the MapRenderer. When a GameObject with a MapPin component is chilided to the MapRenderer, then the MapRenderer will take over positioning the GameObject based on the LatLon and altitude value specified in the MapPin. Then all you'll need to do is make sure the Camera's MapPin component LatLon is kept up to date via some other script.

With that approach though, the Camera's GameObject would be disabled if it goes outside the bounds of the map. That may or may not be a good thing.

If that doesn't work, the slightly more involved approach is to just synchronize the camera's position every frame using the extension methods of the MapRednerer which allow you to convert between LatLonAlt coordinates and Unity world space positions. Specifically, see the methods [TransformLatLonAltToWorldPoint](https://github.com/Microsoft/MapsSDK-Unity/wiki/Microsoft.Maps.Unity#maprenderertransformextensions) and [TransformWorldPointToLatLonAlt](https://github.com/Microsoft/MapsSDK-Unity/wiki/Microsoft.Maps.Unity#maprenderertransformextensions).

Hope that helps!

**Comment by keenanwoodall** [comment]
Maybe I'm misunderstanding your solution, or I didn't explain what I'm trying to do well.

I have a camera that orbits a spherical globe. I want its view to match the 2d view of the map renderer as best as possible. Matching the lat/lon is easy, but getting the 3d camera's distance from the globe to match the map renderer's altitude has proven difficult.

I figured there must be some conversion method between zoom level and altitude from sea level that I could use to set the radius of my globe's camera position.

![2019-12-05_13-40-51](https://user-images.githubusercontent.com/9631530/70267848-dff89480-1764-11ea-8c9a-e22c8610aca4.gif)

**Comment by kircher1** [comment]
Thanks for the gif! I understand now. In this case, I would use the second option. Run the MapRenderer's Camera's position through the WorldToLatLonAlt method. That will give you the camera's altitude in real-world meters, i.e. the value be very large at these zoomed out views.

As to how you translate that altitude back to your global camera, that will be up to you, but there should be some linear equation to map that altitude value to a radius for the camera by relating the earths radius in real-world meters to the radius in Unity meters. I think it would look like this `globeCameraAltitude = mapRendererCameraAltitude * (globeRadiusInUnityWorldSpace / 6371000 /* earth's radius in meters */);`.

**Comment by keenanwoodall** [comment]
Thanks, this is exactly what I needed 👍

**Comment by keenanwoodall** [comment]
I've got conversion from "map space" to "globe space" working well using `TransformWorldPointToLatLonAlt` but I also need to to convert back. There isn't a way I can tell to set the map renderer's altitude directly and I can't find a way to convert from altitude to zoom level, so I'm quite stumped.

Ideally there'd be a pair of methods for converting between the two without even needing a map renderer. If this functionality exists internally could it be exposed? Or is there another way I can set the map renderer's altitude?

**Comment by kircher1** [comment]
At zoom level 1, the MapRenderer is a 1x1 square in Unity space (assuming no additional scaling), and if Mercator distortion is ignored, the MapRenderer's global dimensions are EarthRadius x EarthRadius. Each increment in zoom level halves the global dimensions of the map.

While it's kind of conceptually strange to relate altitudes and zoom levels, I see what you're getting at. The equation to do that I believe, working backwards from the above assumptions, would look like this:
zoomLevel = Log2(EarthRadius / altitude /* meters */) + 1;

**Comment by keenanwoodall** [comment]
Got it working thanks. As you say the mercator distortion is ignored so panning doesn't change the altitude as you approach the poles. If necessary I think there's a chance I can figure out how to compensate for mercator distortion in the calculations, but I this looks fine for now.

![2019-12-08_19-53-54](https://user-images.githubusercontent.com/9631530/70401263-7b536900-19f4-11ea-8904-73351270c297.gif)

If anyone needs them, here's the final utility methods I ended up with
```cs
public const double EarthRadius = 6.371d * 1000000d;
public const double EarthCircumference = 40.075 * 1000000d;

public static float AltitudeToZoomLevel(double altitude)
{
	return (float)Math.Log(EarthCircumference / altitude, 2d) + 1f;
}
public static double ZoomLevelToAltitude(float zoomLevel)
{
	return EarthCircumference / Math.Pow(2d, zoomLevel - 1d);
}
```

**Comment by kircher1** [comment]
Awesome, looks great! In case you want to account for Mercator distortion, it should be fairly easy to incorporate that into the equation. Mercator scale for a given coordinate = `1 / Math.Cos(Math.Abs(latitudeInRadians));`

At the equator, no distortion exists, i.e. globe and map is 1:1. At the limit of the Mercator map which is +-85  degrees, the distortion is about 11x!

**Comment by keenanwoodall** [comment]
Perfect! 👌
