### ISSUE TITLE
Building from rooftop data

### ISSUE THREAD

**Issue by lovisio** [microsoft/MapsSDK-Unity#36]
Hello, 
I would need to use the map of Paris in 3D, but apparently its not available . Will you plan to integrate it ?

Also, because you probably have the data of building, will it be possible to generate it from the rooftop data ?

Thanks you

**Comment by kircher1** [comment]
Correct, there is currently no photo-realistic 3D representation of Paris available as part of the maps data. If there is a public source for such data, that would be interesting!

Bing Maps does have data for extruded buildings in Paris. This is a more symbolic representation. This data is not currently available through the SDK but may be in the future. 
![image](https://user-images.githubusercontent.com/20366429/70560309-37b84680-1b3d-11ea-96bc-5d03f9605861.png)
__From Windows "Maps" app__

**Comment by DanielFlamino** [comment]
> [...] Bing Maps does have data for extruded buildings in Paris. This is a more symbolic representation. This data is not currently available through the SDK but may be in the future. [...]

In the meantime, do you happen to know if there's any way to access the data for those extruded buildings even if that means that we'd have to implement the renderer ourselves?
