### ISSUE TITLE
Map Pins are put on 'Default' layer when enabled

### ISSUE THREAD

**Issue by keenanwoodall** [microsoft/MapsSDK-Unity#37]
**Describe the bug**
I'm using pins for POIs and need to put them on a separate layer to register input, but the layer is set to 'Default' constantly when the pin is enabled. It also appears that the children of the pin have their layer changed as well, but only when initially added to the layer.

**Expected behavior**
The layer of the pin game object and its children should not be changed by Map Renderer or Map Pin Layer.

**Environment (please complete the following information):**
 - Unity version: 2019.2.14f1
 - Maps SDK NuGet Package version: 0.4.2

**Comment by kircher1** [comment]
The behavior here changed in 0.4.2. Now by default MapPins are synchronized with the layer of the MapRenderer. 

If this functionality isn't needed though, you can disable it by setting the [IsLayerSynchronized](https://github.com/microsoft/MapsSDK-Unity/wiki/Microsoft.Maps.Unity#pinnable) field to false, which should be doable in the MapPin editor or via script.

**Comment by keenanwoodall** [comment]
Got it, thanks
