### ISSUE TITLE
Installation questions

### ISSUE THREAD

**Issue by andybak** [Microsoft/MapsSDK-Unity#4]
Almost every other Unity repo on Github is installed in one of a handful of ways:

1. Clone it and open it as a project.
2. Install it as a Unity UPM package (currently rare but will soon become the standard way as it's the only sane way to handle dependencies in Unity)
3. Clone it and drag it into an existing project
4. Download a .unitypackage from the releases page and import it into Unity.

I've skim read the getting started and readme for this and I'm rather confused. I understand the need for an API key but I'm not clear if I need to use NuGet or not (preferably not..). 

I'm going to soldier on but this part of the set up could be a lot clearer. Ideally go for install method 1 or 2 above.

**Comment by kircher1** [comment]
Basically, we support options 1 and 4. The UPM packaging is definitely interesting and we'll be looking into that as Unity appears to be moving the direction...

Option 1: The repo can be cloned, which includes a project under the SampleProject directory, which is pre-configured to pull the NuGet package.

Option 4: Alternatively, you can download the .unitypackage from the Releases page which include the necessary infrastructure to pull the NuGet package.

I'll see if I can elaborate more on this in the getting started docs. These options are briefly explained [here](https://github.com/Microsoft/MapsSDK-Unity/wiki/Getting-Started#importing-the-sdk)

**Comment by kircher1** [comment]
I've updated the [getting started](https://github.com/Microsoft/MapsSDK-Unity/wiki/Getting-started) page; Hopefully it's clearer now which paths can be used to get up and running!
