### ISSUE TITLE
Sample project runs 30 frames/second and scene is on the same level as the camera.

### ISSUE THREAD

**Issue by Yonet** [microsoft/MapsSDK-Unity#41]
**Describe the bug**
Currently, scenes run 30 frames/sec on HoloLens 2. How can I improve performance?
Also, the scene is on the same level as the camera, so the map is above eye level. See link for the captured video from HoloLens 2: https://msit.microsoftstream.com/video/200886bd-29b8-4800-9a1b-69094c3ded94

**To Reproduce**
1. Open and build the City Tour example.
2. Deploy it to HoloLens 2
3. See the performance monitor for the framerate.

**Expected behavior**
Scene to render below the eye level and animation to run 60 fps.

**Screenshots**
https://msit.microsoftstream.com/video/200886bd-29b8-4800-9a1b-69094c3ded94

**Environment (please complete the following information):**
 - Unity version: [e.g. 2018.4.15f1]
 - Maps SDK NuGet Package version: [e.g. 0.5.0]

Thanks!

**Comment by kircher1** [comment]
Thanks for the feedback!

Some manual modifications you can make to the scene that should improve perf are:
* Disabling `Receive shadows` and `Cast shadows` options in the MapRenderer's render settings.
* Disable `MapRaycastProviderRegistration` component. This will cause a raycast to happen every frame which is somewhat CPU intensive.

The camera is located at floor level for VR, but I believe in AR devices with a floor reference, this camera position then corresponds to the starting location of the HMD. A quick way to accomadate HL2 is to offset the camera vertically along the y axis by a meter or so. 

Other scene modifications would probably be turning off the floor plane, to avoid the rendering overhead.

Let me know if this helps!

**Comment by kircher1** [comment]
On a broader note, we need to do some work on the sample project to work better with HL2 and AR devices in general.

Right now, the "WeatherCubeExample" is the only scene that is really more of an AR experience. 

The other scenes are really geared towards VR, but ideally, would work on any mixed reality device. On AR devices, the scenes should hide the floor geometry, and allow the user to place the map within their environment. I believe MRTK provides helpers to read back the reconstructed geometry so the scenes should be leveraging that information to allow the user to place the map.

From a performance perspective, when on AR devices it is probably best to turn off the more expensive graphical features as well to reduce GPU overhead, e.g. disabling shadows. Again, something that would need to be determined at runtime based on the type of device.

These are the sorts of the things we will look at improving in the future, but feel free to submit your own PRs if you find yourself making these changes. Thanks!!
