### ISSUE TITLE
Add reference modes to MapRenderer.Raycast API?

### ISSUE THREAD

**Issue by CubicVR** [microsoft/MapsSDK-Unity#42]
**Is your feature request related to a problem? Please describe.**
Currently MapRenderer.Raycast api will raycast to everything on the map. It would be helpful to add a method that has reference modes similar to MapPin.AltitudeReference. For example being able to sketch only on the terrain while ignoring buildings. Or when dragging 3D models onto the map, ability to cast only onto the terrain...

**Describe the solution you'd like**
Add a Raycast method to the existing API that does this:
public bool Raycast(Ray ray, out MapRendererRaycastHit hitInfo, RaycastReference raycastReference);

Options could include RaycastReference.Surface and RaycastReference.Terrain.

**Describe alternatives you've considered**
Not a must have but more granular filters would be also useful if there are ways to identify vegetation, terrain, water, buildings, roads etc.

**Comment by kircher1** [comment]
Noted, thanks for the feature request!
