### ISSUE TITLE
Missing Script on Small Map Pin's Cube prefab

### ISSUE THREAD

**Issue by adityosnrost** [microsoft/MapsSDK-Unity#46]
**ISSUE**

Cube object on Small Map Pin prefab is missing the script based on these images below:
![image](https://user-images.githubusercontent.com/8223156/76853662-53d82c00-6880-11ea-800d-a90d7f22a8ca.png)

I do not know what the script for.

**REPRODUCED THE ISSUE**

1. Create new project
2. Import Nuget For Unity
3. Install MRTK v2.3.0 and MapsSDK nuget package
4. Import examples package from release packages (Only tick the examples)
5. Open SmallMapPin prefab
6. Look at child object name cube

**Expected Behavior**

No missing script

**Environment**

Unity 2019.2.21f1
MRTK v2.3.0
MapsSDK 0.5.1

**Comment by kircher1** [comment]
It looks like it's missing MRTK' `Interactable` component.

    4. Import examples package from release packages **(Only tick the examples)**

If you only tick the examples (Microsoft.Maps.Unity.Examples), they do depend on MRTK functionality like this Interactable component. The asset package already contains everything that is required to run the examples so hopefully by leaving everything checked the missing script error goes away.

If it was an issue with this version's particular asset package, try the latest 0.6.0. I don't see this issue when expanding the new asset package into a blank 2018.4.21f1 project.
