### ISSUE TITLE
Hope to have a spherical map

### ISSUE THREAD

**Issue by AhrenLi** [microsoft/MapsSDK-Unity#47]
Hello, I am researching World Map Globe Edition 2 (https://assetstore.unity.com/packages/tools/gui/world-map-globe-edition-2-150643), vts-browser-unity-plugin (https : //github.com/melowntech/vts-browser-unity-plugin), I hope to have a spherical map, which will be extremely convenient, thank you!

**Comment by kircher1** [comment]
Thanks for the suggestion! It is a fairly significant change in order to support this, but I'll definitely be tracking this request as it's clearly a good feature.
