### ISSUE TITLE
HoloLens(1st) Cannot Load Map

### ISSUE THREAD

**Issue by tisaud** [Microsoft/MapsSDK-Unity#5]
This project can run well in Unity(2018.3.7f),but it cannot load map in HoloLens(1st). 
Target Sdk Version: 18362 ,Min Sdk Version: 10240. Scripting Backend:IL2CPP

**Comment by kircher1** [comment]
Hello, thanks for reporting!

I've been unable to reproduce this using 2018.3.7, IL2CPP backend, target/min of 1836/10240, using HoloLens 1 (OS version 17763.380).

I used the WeatherCube sample scene to confirm the map data is loading.

Ensure you have supplied the Bing Maps developer key on the MapRenderer in the scene, and ensure you have an active internet connection on the HoloLen, Both would be required to stream the map data. 

To further investigate, feel free to share the UnityPlayer log which can be pulled off the HoloLens using the device portal's file explorer. Check the LocalAppData folder and under the corresponding app folder, there should be a TempState folder with a UnityPlayer.log.

**Comment by kircher1** [comment]
Please reopen if the map is still not loading.
