### ISSUE TITLE
Feature: Elevation Exaggeration / Scale

### ISSUE THREAD

**Issue by xwipeoutx** [microsoft/MapsSDK-Unity#50]
We're after the ability to exaggerate terrain, to make flat areas a little more interesting, and small hills more obvious.

I'd like to have an option on the map renderer to set the "elevation scale" - a number greater than 0 which describes how much to exaggerate elevation by.

This would affect terrain and also pin altitudes, and any calls to `TransformLatLonAltToWorldPoint`

I've done a lot of this manually myself, but the change to 0.6.1's collider volume broke it, and without access to the depth-writing logic for the collider volume, I can't get much further (well, yet).

My in-shader fix for the terrain was essentially multiplying `_ElevationTexScaleAndOffset.w` by my own `_ElevationScale` in calls to `CalculateElevationOffset` and `FilterNormal`, which I'm happy to share back (though I have a lot of other changes in my shader too)

**Comment by xwipeoutx** [comment]
I've put up a hacky fix for this at 
https://github.com/xwipeoutx/MapsSDK-Unity/tree/spike/elevation-exaggeration

The gist of it is

* In the 2 render shaders (terrain, clipping volume), scale their Y value by the elevation scale
* In the clipping distance shader, adjust the view matrix so that it doesn't clip terrain that's too high (I just guessed this one)

It's relatively low impact, when all is said and done - the clipping shader is the obvious hack, because I can't just change that matrix in the C# codes.

**Comment by kircher1** [comment]
Addressed in 0.7.0. Thanks!
