### ISSUE TITLE
Filename too long error

### ISSUE THREAD

**Issue by Yonet** [microsoft/MapsSDK-Unity#51]
**Describe the bug**
File names are too long for git. Ex error message:

`error: unable to create file SampleProject/Assets/MixedRealityToolkit.Providers/WindowsMixedReality/Shared/DotNetAdapter/.bin/net46/Microsoft.Windows.MixedReality.DotNetWinRT/Editor/Microsoft.Windows.MixedReality.DotNetWinRT.Editor.asmdef: Filename too long`
`fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'`

**To Reproduce**
1. Clone the repo in your local environment terminal.
`git `
2. The above git error message is printed.
3. git status result seen in image below.

**Expected behavior**
Clone files and checkout master.

**Screenshots**
![gitfail](https://user-images.githubusercontent.com/3523671/81020323-651fcc80-8e1d-11ea-881f-e7bedb5c60be.png)

**Environment (please complete the following information):**
Windows 10
Current repo clone.

**Comment by kircher1** [comment]
I haven't ran into this, but it may be caused by how git is configured to manage longer path names. It sounds like long path support can be added to this command: `git config --system core.longpaths true`

**Comment by Yonet** [comment]
It is also solved by MRTK 2.4.0. I'll close, thanks.
