### ISSUE TITLE
Example use case for WaitForMapSceneAnimation?

### ISSUE THREAD

**Issue by HKBSC** [microsoft/MapsSDK-Unity#53]
Could you provide an example of how to use WaitForMapSceneAnimation?

I am trying to have a separate script turn a bool false after calling SetMapScene then true once WaitForMapSceneAnimation returns false. 

Thanks.

**Comment by kircher1** [comment]
WaitForMapSceneAnimation is intended to be yielded in a  coroutine. After yield returns, the animation has been completed.

The CityTourExample scene from the SampleProject uses this API to animate between a list of locations. See [SeattleTour.cs](https://github.com/microsoft/MapsSDK-Unity/blob/master/SampleProject/Assets/Microsoft.Maps.Unity.Examples/CityTourExample/Scripts/SeattleTour.cs). Relevant snippet below:

``` C#
    private IEnumerator RunTour()
    {
        yield return new WaitForSeconds(5.0f);

        while (isActiveAndEnabled) // loop the tour as long as we are running.
        {
            foreach (var scene in MapScenes)
            {
                yield return _map.SetMapScene(scene);

                yield return new WaitForSeconds(3.0f);
            }
        }
    }
```

Hope that helps!
