### ISSUE TITLE
ZoomToMapPin and ZoomToClusterPin Assertion Fail error

### ISSUE THREAD

**Issue by Yonet** [microsoft/MapsSDK-Unity#55]
**Describe the bug**
When running the map pin examples has "Assertion Failed" errors on lines below:
https://github.com/microsoft/MapsSDK-Unity/blob/397b2775fd6b380bfc510123b744c463ba41a460/SampleProject/Assets/Microsoft.Maps.Unity.Examples/MapPinExample/Scripts/ZoomToClusterMapPin.cs#L21
https://github.com/microsoft/MapsSDK-Unity/blob/397b2775fd6b380bfc510123b744c463ba41a460/SampleProject/Assets/Microsoft.Maps.Unity.Examples/MapPinExample/Scripts/ZoomToMapPin.cs#L21

**To Reproduce**
1. Check out the latest examples, version: 0.7.1
2. Open the Map Pin Example scene and add the developer key.
3. Press play on the editor window.

**Expected behavior**

**Screenshots**
![MapPinErr](https://user-images.githubusercontent.com/3523671/81902307-c4e04b00-9574-11ea-8fc5-4786ffdb1f53.png)

**Environment (please complete the following information):**
 - Unity version: 2019.3.13f1
 - Maps SDK NuGet Package version: 0.7.1

Thanks!

**Comment by kircher1** [comment]
I think the scripts ZoomToMapPin and ZoomToClusterMapPin have somehow become swapped in the corresponding MapPin/ClusterMapPin prefabs used by this scene: 
![image](https://user-images.githubusercontent.com/20366429/81962727-fa168880-95c8-11ea-93dc-ec7d56d3c4bd.png)

Seems like the prefabs just need to be corrected.
