### ISSUE TITLE
Error in MapRendererTransformExtensions Method Summary text

### ISSUE THREAD

**Issue by HKBSC** [microsoft/MapsSDK-Unity#60]
**Describe the bug**
Summary text for the following methods are identical in both the MapRendererTransformExtensions .cs file and getting started documentation:
- TransformWorldPointToLatLonAlt
- TransformLatLonAltToWorldPoint

TransformLatLonAltToWorldPoint summary should be the other way around.

See below code snippet:

        /// <summary>
        /// Transforms an XYZ point in world space to a <see cref="LatLonAlt"/>.
        /// </summary>
        public static LatLonAlt TransformWorldPointToLatLonAlt(this MapRenderer mapRenderer, Vector3 pointInWorldSpace)
        {
            var mercatorPosition =
                TransformLocalPointToMercatorWithAltitude(
                    mapRenderer,
                    pointInWorldSpace,
                    out var altitudeInMeters,
                    out var mercatorScale);

            var latLon = LatLon.FromMercatorPosition(mercatorPosition);
            return new LatLonAlt(ref latLon, altitudeInMeters);
        }

        /// <summary>
        /// Transforms an XYZ point in world space to a <see cref="LatLonAlt"/>.
        /// </summary>
        public static Vector3 TransformLatLonAltToWorldPoint(this MapRenderer mapRenderer, LatLonAlt location)
        {
            // Can compute XZ coords in local space from the Mercator position and map center.
            var mercatorPosition = location.LatLon.ToMercatorPosition();
            var mercatorPositionRelativeToCenter = mercatorPosition - mapRenderer.Center.ToMercatorPosition();
            var equatorialCircumferenceInLocalSpace = Math.Pow(2, mapRenderer.ZoomLevel - 1);
            var localSpaceXZ = equatorialCircumferenceInLocalSpace * mercatorPositionRelativeToCenter;

            // Altitude to local y value.
            var offsetMapAltitudeInMeters = location.AltitudeInMeters - mapRenderer.ElevationBaseline;
            var mercatorScale = 1.0 / Math.Cos(location.LatLon.LatitudeInRadians);
            var altitudeInLocalSpace = offsetMapAltitudeInMeters * mercatorScale * (equatorialCircumferenceInLocalSpace / EquatorialCircumferenceInWgs84Meters);

            var pointInLocalSpace =
                new Vector3(
                    (float)localSpaceXZ.X,
                    (float)(altitudeInLocalSpace + mapRenderer.LocalMapHeight),
                    (float)localSpaceXZ.Y);

            return mapRenderer.transform.TransformPoint(pointInLocalSpace);
        }

**Comment by kircher1** [comment]
Thanks for catching that. The method names are correct but TransformLatLonAltToWorldPoint's description is indeed backwards. We'll fix this in the next release.

**Comment by kircher1** [comment]
Fixed in 0.9.0. I've also identified some bugs in the transformation extension methods. Those have been fixed as well.
