### ISSUE TITLE
Modify MapPin GameObject's size

### ISSUE THREAD

**Issue by darthcarlos90** [microsoft/MapsSDK-Unity#61]
Is there a way I can programmatically change the size of a GameObject that has the MpPin script attached?  When I select the Use Real World Scale it is too small to be visible by the user. When I deselect it, the GameObject appears so big it blocks out most of the map. Is there any configuration I left out?

Thanks in advance.

**Comment by kircher1** [comment]
To do this, you can use the GameObject hierarchy. At the top level node of your GameObject, put the MapPin component. Add a child GameObject, you can call it something like "Root". While it's a child of the MapPin GameObject, it is really the root of your content, i.e. it's children would be a heirarchy of GameObjects that represent what you want to render on the map. If it's just a simple model (like one MeshRenderer), the "Root" object itself could contain the content. Whichever way, the "Root" transform can be used to scale your content without the MapPin's scaling affecting it.

An example of this can be found in the [SampleProject](https://github.com/microsoft/MapsSDK-Unity/tree/master/SampleProject).

See the SmallMapPin.prefab.

![image](https://user-images.githubusercontent.com/20366429/84466305-f90b6200-ac2d-11ea-8c3e-3653bab3afc0.png)

**Comment by kircher1** [comment]
The realistic scale by the way is intended for the case where you have a model scaled to the realworld, e.g. a accurate model of a house or building, and you want to pin that to the map. Using the realworld scaling option will then scale that object so it maintains it's actual dimension in real-world meters, so unless the object is massive it would quickly disappear when zooming out.
