### ISSUE TITLE
Please add example scene for requesting Http Map Tile Imagery using Bing Maps API's

### ISSUE THREAD

**Issue by HKBSC** [microsoft/MapsSDK-Unity#63]
**Is your feature request related to a problem? Please describe.**
Since default texture tiles can currently only show aerial imagery, please add sample scene showing how to implement Bing Maps API workaround to get symbolic map tile imagery / route / pin etc.

**Comment by kircher1** [comment]
The DefaultTextureTileLayer's symbolic, roads and labels options are working in 0.8 and later.

The SampleProject has a sample scene called [HudExample](https://github.com/microsoft/MapsSDK-Unity/tree/master/SampleProject/Assets/Microsoft.Maps.Unity.Examples/HudExample) which exercises the symbolic and aerial options on the DefaultTextureTileLayer. [MapPinExample](https://github.com/microsoft/MapsSDK-Unity/tree/master/SampleProject/Assets/Microsoft.Maps.Unity.Examples/MapPinExample) shows pinning/clustering functionality.

Routing APIs and line rendering are not currently supported, but certainly something we'd like to add!

**Comment by kircher1** [comment]
Please reactive if you find those samples are not sufficient to demonstrate the custom tile imagery sources.
