### ISSUE TITLE
HTTP Texture Tile Layer - Server Switching

### ISSUE THREAD

**Issue by Neutrinora** [microsoft/MapsSDK-Unity#70]
**Is your feature request related to a problem? Please describe.**

> Cannot use multiple URL sources for a single HTTP Texture Tile Layer.

**Describe the solution you'd like**

> Ability to use multiple URL sources on a single HTTP Texture Tile Layer.

**Describe alternatives you've considered**

> Alternatively, instead of using multiple URL sources, ability to use another replacement string {s} which refers to available server codes.

//Input via inspector
string[] serverCodes = new string[3] { "a","b","c" };

//URL source
https://{s}.tile.server.com/{z}/{x}/{y}.png

//Results
https://a.tile.server.com/6/36/24.png
https://b.tile.server.com/6/36/24.png
https://c.tile.server.com/6/36/24.png

**Additional context**

Possible conflict:
- Treating a,b,c as different textures on cache systems

Possible feature:
- Adaptive server(s) selection based on download speeds

Best regards

**Comment by kircher1** [comment]
Added in 0.9.2.
