### ISSUE TITLE
Edges on Borders results Unpleasant Visuals 

### ISSUE THREAD

**Issue by Neutrinora** [microsoft/MapsSDK-Unity#72]
These edges are visible in Game view when using an Edge Fade value less than 0.0025f (also value relative to game view resolution).
Is there any way to hide them without using Edge Fade, or to keep them resolution-independent.
![polygons](https://user-images.githubusercontent.com/6050906/85920955-f9883780-b880-11ea-831d-a98702abb566.png)
![polygons2](https://user-images.githubusercontent.com/6050906/85920956-fb51fb00-b880-11ea-97b3-5750f20cb972.png)

Real source of problem. I thought that linelike-planes are some requirement for SDK itself..
![polygons3](https://user-images.githubusercontent.com/6050906/85920957-fbea9180-b880-11ea-9568-fa6b86265d6d.png)
![polygons4](https://user-images.githubusercontent.com/6050906/85920958-fc832800-b880-11ea-8a0a-e8ab082d5814.png)

**Comment by kircher1** [comment]
It looks like the mitigation we have for this only applies to the shader code that handles the edge clipping for a circular map shape, not a block shape like this.

Navigate to the package of the SDK and go to the `Runtime/SupportingScripts/Shaders` directory. Open `ClippingVolume-MapsSDK.cginc`, and try modifying line 48 to look _**like this**_:

`float distanceToPlane = abs(dot(planeNormal, planePositionToWorldPosition)) - _ClippingVolumeSize[planeId]` _**`+ 0.005 * isSkirt * _ClippingVolumeSize.x;`**_

If it's slightly better but not solved, try increasing the 0.005 value.

Also, others have reported that changes to the package's contents will get overwritten with the published version when opening/closing Unity, but we can get this shader change pushed into a future release if it does the trick.

**Comment by kircher1** [comment]
Added this mitigation to 0.9.2.
