### ISSUE TITLE
Map Unity Package Manager URL is not valid

### ISSUE THREAD

**Issue by TechArtistG** [microsoft/MapsSDK-Unity#75]
**Describe the bug**
When following the Masp SDK install instructions here:
https://github.com/Microsoft/MapsSDK-Unity/wiki/Getting-started

It says to add some data to the your project's manifest.json file which adds a package URL.

After adding the data to manifest.json and restarting Unity and opening a project the Maps SDK still isn't available in the Package Manager.

If you try and visit the given package URL in a browser https://unity.virtualearth.net/npm/registry/ an error is returned:
`<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:81c78c93-601e-00bb-2e40-59493f000000 Time:2020-07-13T18:11:07.3918076Z</Message>
</Error>`

**To Reproduce**
1. Follow install instructions from here https://github.com/Microsoft/MapsSDK-Unity/wiki/Getting-started
2. Follow guide for Option 2
3. Open the Unity Package Manager, no new packages will be available

**Expected behavior**
Maps SDK for Unity should be available in the package manager after following install instructions

**Environment (please complete the following information):**
 - Unity 2019.3.2f1

**Comment by kircher1** [comment]
Thanks for the bug report... That error message on the registry URL itself is expected. Can you access these URLs?
* https://unity.virtualearth.net/npm/registry/com.microsoft.maps.unity
* https://unity.virtualearth.net/npm/registry/-/all

**Comment by kircher1** [comment]
I haven't been able to reproduce after clearing Unity's caches and installing the package into a new project as per the instructions.

Some things to check are that 1) "All packages" are being shown and 2) "Show Preview Packages" is enabled under the Advanced settings.

Lastly, I noticed that even after enabling these settings the package name didn't show up until I hit the refresh button at the bottom of the panel.

![image](https://user-images.githubusercontent.com/20366429/87342490-2b93cd80-c500-11ea-82eb-7719a714f3b9.png)

The only other difference here may be the Unity editor version. I recommend trying 2019.4 if none of these suggestions do the trick.

**Comment by kircher1** [comment]
Please reactivate if you're still running into package installation issues. Thanks!
