### ISSUE TITLE
XR: OpenVR Error! OpenVR failed initialization with error code VRInitError_Init_PathRegistryNotFound: "Installation path could not be located (110)"!

### ISSUE THREAD

**Issue by yosun** [microsoft/MapsSDK-Unity#76]
**Describe the bug**
OpenVR should not be required as Maps should be independent of VR specific applications. 

XR: OpenVR Error! OpenVR failed initialization with error code VRInitError_Init_PathRegistryNotFound: "Installation path could not be located (110)"!

**To Reproduce**
1. Download repo.
2. Open in Unity 2019.4.4 with defaulting settings
3. Press play

**Expected behavior**
This error should not occur

XR: OpenVR Error! OpenVR failed initialization with error code VRInitError_Init_PathRegistryNotFound: "Installation path could not be located (110)"!

**Screenshots**

**Environment (please complete the following information):**
 - Unity version: 2019.4.4f1
 - Maps SDK NuGet Package version: [e.g. 0.1.1]

**Additional context**

**Comment by kircher1** [comment]
This error can be ignored. If OpenVR is not available, the MRTK hand simulation should automatically be used instead. The camera in that case can be controlled with WASD keys. 

You can disable VR support also to remove this error message in the player settings.
