### ISSUE TITLE
Why are Local Map Dimensions capped at 3x3? 

### ISSUE THREAD

**Issue by yosun** [microsoft/MapsSDK-Unity#77]
Why are Local Map Dimensions capped at 3x3?

**Comment by kircher1** [comment]
The SDKs current logic chooses the data to render purely based on the zoom level of the map. so as the dimension and area that the map displays for a given zoom level gets larger, the number of network requests, processing and draw calls all increase. 3x3m is the cutoff that was chosen to prevent pushing this too far. Going beyond this may work on some devices with good network speeds, fast GPUs, etc, but it will fall over eventually.

This dimension should work for using the map in a tabletop scenario. Understandably for immersive views, it is not large enough. #2 is intended to track that although there may be a halfway step where the dimension is increased to a higher threshold than 3x3 before a full immersive mode is enabled.

If you are looking to get the highest fidelity experience now within these dimension constraints, you can turn the quality setting up to 1.0 and if you need the map to cover a larger area in the scene, the transform's scaling can be used.

**Comment by yosun** [comment]
As a work-around to the 3x3 limitations, would just using multiple map renderers work? how does one convert zoom percent to lat/lng differences to load in the neighboring map renderer (to create a seamless map)?
