### ISSUE TITLE
Unity WebGL : uncaught exception: abort

### ISSUE THREAD

**Issue by Ristophonics** [microsoft/MapsSDK-Unity#78]
I'm getting the following error when opening my webgl build in various browsers and I'm not sure if it is related to this SDK.

Anyone shed some light on this for me please?

Here is the error: **An error occurred running the Unity content on this page. See your browser JavaScript console for more info. The error was:
uncaught exception: abort("To use dlopen, you need to use Emscripten's linking support, see https://github.com/kripken/emscripten/wiki/Linking") at jsStackTrace (Web.wasm.framework.unityweb:8:22313)**

The stack trace is: 

**stackTrace (Web.wasm.framework.unityweb:8:22484)
onAbort@file:///F:/FileStorage/GITHUB/XRMeeting/Builds/Web/Build/UnityLoader.js:4:11118
abort (Web.wasm.framework.unityweb:8:617461)
_dlopen (Web.wasm.framework.unityweb:8:184219)
@blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[93272]:0x1c1644e (blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[94716]:0x1c57201)
@blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[38893]:0xeff7eb (blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[38892]:0xeff780)
@blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[38891]:0xeff754 (blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[30732]:0xdaaf41)
@blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[95871]:0x1c8df32
UnityModule [UnityModule/Module.dynCall_iiiii] (Web.wasm.framework.unityweb:8:567267)
invoke_iiiii (Web.wasm.framework.unityweb:8:371360)
@blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[93880]:0x1c34863 (blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[93159]:0x1c12601)
@blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[5883]:0x2c700b (blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[5882]:0x2c6f34)
@blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[10987]:0x4baaa2 (blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[10985]:0x4ba0c8)
@blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[14500]:0x64b8b1 (blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[5666]:0x2b66f1)
@blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[10990]:0x4bb20f (blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[10982]:0x4b97c5)
@blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[10983]:0x4b9b80 (blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[10978]:0x4b909a)
@blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[12258]:0x52c16f (blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[12257]:0x52be58)
@blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[12255]:0x52bd3f (blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[12251]:0x52b724)
@blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[12244]:0x52b259 (blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[12107]:0x51896f)
@blob:null/06a36885-1d82-431c-92ba-8681e6736451 line 8 > WebAssembly.instantiate:wasm-function[12106]:0x518506
UnityModule [UnityModule/Module._main] (Web.wasm.framework.unityweb:8:545955)
callMain (Web.wasm.framework.unityweb:8:616251)
doRun (Web.wasm.framework.unityweb:8:616924)
run (Web.wasm.framework.unityweb:8:617103)
runCaller (Web.wasm.framework.unityweb:8:615878)
removeRunDependency (Web.wasm.framework.unityweb:8:28777)
processDataJob@file:///F:/FileStorage/GITHUB/XRMeeting/Builds/Web/Build/UnityLoader.js:4:5421
schedule/i.callback@file:///F:/FileStorage/GITHUB/XRMeeting/Builds/Web/Build/UnityLoader.js:3:19246**

**Comment by Ristophonics** [comment]
This might be because I am trying to write to the harddrive using Save(), which is not allowed. If I can confirm this I will close and comment. Thanks!

**Comment by kircher1** [comment]
The SDK is unlikely to work with WebGL. However, I haven't tried it personally. The official platforms we are targeting are specifically Windows/Android/iOS.

If you are able to get the map running on WebGL tho, let us know!

**Comment by Ristophonics** [comment]
good to know. Thanks for the response! I've got the Quest and PC versions running well and cross-platform. Looks like there are issues going with the WebGL build that I had not anticipated. I am also using Photon PUN2 to network the Map and provide VoIP so that complicates the cross-platform WebGL side too. I am going to ditch it for now and call this one closed. Thank you!!!
