### ISSUE TITLE
Help with MapInteractionController

### ISSUE THREAD

**Issue by jasonhbartlett** [microsoft/MapsSDK-Unity#80]
Hello,
This is for HoloLens 2

I added the MapInteractionController, MapRaycastProviderRegistration, and MapInteractionHandler scripts to the Map and I'm able to Pan around with no problem.  Works good.  I have 2 Questions that I can't seem to find the solutions for:

1. What do I call to toggle the movement from Panning to Zooming?

2. Is there a Callback for when the MapInteractionController Panning or Zooming is triggered?  (My app has GPS that will keep the map centered on the users position, but I need to know when the user starts Panning or Zooming, so I can disable the centering when the user is scrolling around.  Then when they hit the Home button, it will set centering back to true and animate back to their GPS position.

Thanks for any help you can provide!

**Comment by kircher1** [comment]
For 1) the zooming functionality in the MapInteractionHandler is setup to work with thumbstick actions from hand controllers. These input actions are assigned via the MRTK config to various controllers' thumbsticks (WMR/OpenVR/Oculus). Unfortunately, unlike the panning, this doesn't translate well to HL2.

The right approach for zooming on HL2 is probably doing something like a two-point zoom interaction on touch screens, i.e. if two rays are hitting the map (say 1 from each hand) the amount of separation in the rays determine the zoom level. In lieu of doing that, a more rudimentary approach could be to use two different buttons for zooming in and out. Voice commands could be an option too.

For 2) no, but that is a good suggestion! I think the MapInteractionHandler probably already has the logic there to easily identify when a pan or zoom begins, so you may be able to modify that script to add an event that gets invoked when a pan starts. See [OnPointerDown](https://github.com/microsoft/MapsSDK-Unity/blob/master/SampleProject/Assets/Microsoft.Maps.Unity.Examples/Common/Scripts/MapInteractionHandler.cs) for the condition when a pan begins. 

Converting to a feature request to track these asks though as these are good additions to the supporting scripts/sample project.

**Comment by jasonhbartlett** [comment]
For 1) Okay, thanks.  For now I'm using my own slightly modified [JoystickController](https://microsoft.github.io/MixedRealityToolkit-Unity/api/Microsoft.MixedReality.Toolkit.Experimental.Joystick.JoystickController.html) class from from the MRTK.  I've turned the Joystick prefab on it's side, disabled all the mesh rendering except for the Grabber at the tip, and this allows the user to grab and drag the grabber up and down to zoom in and out.  It's constrained to the Y axis and the stick values range from -1 to +1 and it springs back to center position whenever its released.  So that's working now for me but hopefully sometime it would be cool to do it with 2-point zoom interaction.

For 2) Ahh... I hadn't realized there was relevant code in that MapInteractionHandler since I thought it was depreciated or something to be replaced by the MapInteractionController.  ? It should be no problem to listen for that OnPointDown event as you pointed out.  

Thanks so much!

**Comment by kircher1** [comment]
Great, and to add some clarity on the breakdown of Handler vs Controller:

The Handler is basically the glue to MRTK and that's why it's only provided as part of the sample project. It "handles" MRTK input events and routes them to... the Controller, which has the core logic and geospatially math to perform pans and zooms. 

Other frameworks could call into the Controllers functionality too to get similar behavior (it has no dep on MRTK). That's why the Controller is part of the SDK itself.

Hope that helps. Good luck!
