### ISSUE TITLE
Why doesn't LatLon / LatLonAlt include a constructor for lat,lon in radians rather than degrees?

### ISSUE THREAD

**Issue by yosun** [microsoft/MapsSDK-Unity#81]
I am curious why degrees is preferred over radians in constructor. Why not have a constructor also for lat lon in radians?

**Comment by kircher1** [comment]
LatLon has a static method for creation from radians, see `LatLon.FromRadians`. Degrees tend to be more common so the constructor itself uses those units as arguments.

I don't think LatLonAlt has a similar method to create from radians, but you can use constructor that takes a LatLon in that case. Hope that helps!
