### ISSUE TITLE
2d map without the Ar stuff ?

### ISSUE THREAD

**Issue by RocinanteGames** [microsoft/MapsSDK-Unity#83]
Hi, first of all, keep up with the good work. Have you ever considered creating a unity package with just the map stuff (map renderer, map pin, etc.) without the ar stuff?

**Comment by kircher1** [comment]
While the sample project does include MRTK and is geared towards mixed-reality, the SDK itself doesn't have a dependency on anything mixed-reality related and can be used for desktop/mobile apps. 

The steps to include the SDK in a Unity project are [here](https://github.com/microsoft/MapsSDK-Unity/wiki/Getting-Started#option-2-start-from-scratch).

If you also want a 2D flat map, i.e. disable 3D terrain and cities, the MapRenderer's TerrainType can be set to [flat](https://github.com/microsoft/MapsSDK-Unity/wiki/Configuring-the-MapRenderer#map-terrain-type).

**Comment by yosun** [comment]
I feel like the strength here is the onboard MRTK support and satellite 3D LIDAR buildings. For just regular 2D stuff, check out Mapbox Unity plugin. (They also have 3D buildings, but they aren't LIDAR scans) 

That said, there could be more examples that utilize traditional touch motifs for phone apps. I've mostly had to puzzle those out myself, and might not be calling the right method for best performance or just hacking it.

**Comment by kircher1** [comment]
The more classic 2D map scenario is in many ways a simplification of what this SDK offers now. For instance, it is currently possible to use a symbolic map representation in a flat 2D mode and layer interesting texture layers on top like weather. The [HUD scene](https://github.com/microsoft/MapsSDK-Unity/wiki/Sample-project#hudexampleunity) from the sample project demonstrates this. Another common scenario is displaying points of interest on a map. [This scene](https://github.com/microsoft/MapsSDK-Unity/wiki/Sample-project#mapserviceexampleunity) demonstrates using MapPins to achieve this.

Both those example scenes rely on MRTK for input though, so I definitely see room for improvement as you point out to provide some better integration with the common interaction models for desktop/phone, e.g. mouse/scroll wheel and touch which can be done by leveraging Unity's built-in Input APIs.

I think there are two ways I can see improving that which is 1) providing some scripts in the SDK itself to support pan/zoom with those classic interaction models, and 2) a sample scene that is non-MR.

**Comment by yosun** [comment]
> The more classic 2D map scenario is in many ways a simplification of what this SDK offers now. For instance, it is currently possible to use a symbolic map representation in a flat 2D mode and layer interesting texture layers on top like weather. The [HUD scene](https://github.com/microsoft/MapsSDK-Unity/wiki/Sample-project#hudexampleunity) from the sample project demonstrates this. Another common scenario is displaying points of interest on a map. [This scene](https://github.com/microsoft/MapsSDK-Unity/wiki/Sample-project#mapserviceexampleunity) demonstrates using MapPins to achieve this.
> 
> Both those example scenes rely on MRTK for input though, so I definitely see room for improvement as you point out to provide some better integration with the common interaction models for desktop/phone, e.g. mouse/scroll wheel and touch which can be done by leveraging Unity's built-in Input APIs.
> 
> I think there are two ways I can see improving that which is 1) providing some scripts in the SDK itself to support pan/zoom with those classic interaction models, and 2) a sample scene that is non-MR.

Converting from the HUD scene to a traditional mobile touch UI could ideally be more automated (and also not MRTK dependent). Also, other map-specific things like MapPin clustering could ideally be independent of MRTK. Their use cases are quite universal / definitely far exceeds that of MRTK.

**Comment by kircher1** [comment]
Yep, I'm envisioning a scene that is basically a top-down view of the map that can be panned or zoomed with touch controls and may have the ability to tap-and-hold to add POIs (which have no MRTK Interactable scripts) and in general would have only dependencies on the SDK and Unity APIs. 

But just to be clear, the SDK itself can be imported into a non-MRTK project without issue. It's just the sample project that has glued them together.

**Comment by kircher1** [comment]
There's now a sample scene in the project which demonstrates how to do a flat map (i.e. for 2D screens). Description [here](https://github.com/microsoft/MapsSDK-Unity/wiki/Sample-project#2dmapexampleunity).
