### ISSUE TITLE
What's the right approach to have a pan-able map

### ISSUE THREAD

**Issue by yosun** [microsoft/MapsSDK-Unity#84]
I was thinking that being able to have a larger grid than 3x3 would make something like the Google Earth panning around feature easier, but [it seems that the grid is capped at 3x3](https://github.com/microsoft/MapsSDK-Unity/issues/77). 

What's the right approach to have a pan-able (3D buildings) map?

**Comment by kircher1** [comment]
I published a branch where I'll be adding some InteractionHandler implementation for touch screen. I'll look at adding an implementation for mouse/scroll wheel interactions next. Check it out [here](https://github.com/microsoft/MapsSDK-Unity/blob/users/briank/input-handler-updates/SupportingScripts/Runtime/Scripts/MapRenderer/MapTouchInteractionHandler.cs).

**Comment by kircher1** [comment]
There's now a sample scene in the project which demonstrates how to do a flat map (i.e. for 2D screens). Description [here](https://github.com/microsoft/MapsSDK-Unity/wiki/Sample-project#2dmapexampleunity).

**Comment by kircher1** [comment]
For this issue I should add there are also scripts in 0.10.0 which facilitate panning and zooming interactions based on Unity input. See MapTouchInteractionHandler and MapMouseInteractionHandler. The sample scene mentioned above leverages these too.
