### ISSUE TITLE
Is it possible to "select a building"? 

### ISSUE THREAD

**Issue by yosun** [microsoft/MapsSDK-Unity#85]
Is it possible to "select a building"? 

(Replace a building with an overlay material, or duplicate building geometry for a temporary "highlighted" object)

**Comment by kircher1** [comment]
I see the usefulness but unfortunately that's not doable through the SDK. The building data itself is loaded in tiled scheme that has no notion of buildings. A tile boundary in fact may cut through the center of one.

**Comment by yosun** [comment]
Checking if any updates has been made here?

**Comment by yosun** [comment]
This would also be useful for "patching up" missing newer buildings with custom 3D models... and is available in similar SDKs like Mapbox and WRLD3D unity plugin's.

**Comment by kircher1** [comment]
For the case of a missing or altered building, if one has a better model to replace it with, using a MapPin with a realistic scale for the new building model would probably be good enough. However, if the old building or terrain would z-fight with the new model, that's not ideal. The feature there would be more of a way to selectively flatten areas on the map so one can place pin their own content there. That's actually an idea tracked by #1, but I don't have any update to report there.
