### ISSUE TITLE
Unity version 2020.1.1f1 Error - ArgumentException: Failed SupportsTextureFormat; format is not a valid TextureFormat

### ISSUE THREAD

**Issue by visose** [microsoft/MapsSDK-Unity#86]
**Describe the bug**
Installed from an empty project using the package manager.
Creating an empty game object and adding the MapRenderer component produces this error:

ArgumentException: Failed SupportsTextureFormat; format is not a valid TextureFormat
UnityEngine.EditorSystemInfo.SupportsTextureFormat (UnityEngine.TextureFormat format) (at <2e6610ed29844f85a37924f81509fe5d>:0)
UnityEngine.SystemInfoShimBase.SupportsTextureFormat (UnityEngine.TextureFormat format) (at <2e6610ed29844f85a37924f81509fe5d>:0)
UnityEngine.SystemInfo.SupportsTextureFormat (UnityEngine.TextureFormat format) (at <2e6610ed29844f85a37924f81509fe5d>:0)
#=zv2JITDRAtmZXRoAMXbzv8LpRsodg..ctor (System.Threading.Tasks.Task`1[TResult] #=zcfokyjU=, System.Threading.SemaphoreSlim #=z8fkoph8HOjCY, #=zg_cDRTM6LUoTEaKSYiNc05U= #=zceu_UPs=, #=zNayfAbDQm5$pg7CEDPdyC4DPLzWF #=znt43Ud84U7ktInC0PUAR3jg=) (at <0a84c34a447f479815da7957e295d17d>:0)
#=zg_cDRTM6LUoTEaKSYiNc05U=.#=z_vhwgHQelT9S (Microsoft.Maps.Unity.ModelTileLayer #=zw_79Xok=) (at <0a84c34a447f479815da7957e295d17d>:0)
#=zg_cDRTM6LUoTEaKSYiNc05U=.#=zkGIQDhP5kv4K[TLayer,TProvider,TProviderList] (Microsoft.Maps.Unity.TileLayerList`1[T] #=z7o55V8Grw8oe, System.Collections.Generic.Dictionary`2[TKey,TValue] #=zlqgIduFbaWI8, #=zg_cDRTM6LUoTEaKSYiNc05U=+#=zunYWV6EotJ0Cv75uRA==[#=zVfUqopU=,#=zkxtYd8I=] #=zqwTvmoz5_ujK, System.Collections.Generic.List`1[T] #=zkmGBR6r5lpk6, System.Boolean #=zzjhb2RA=) (at <0a84c34a447f479815da7957e295d17d>:0)
#=zg_cDRTM6LUoTEaKSYiNc05U=.#=zkGIQDhP5kv4K (Microsoft.Maps.Unity.TextureTileLayerList #=zSAK7PX$HjrRx, Microsoft.Maps.Unity.ElevationTileLayerList #=zh6sd$Irnnd94JYsK9RIzovE=, #=zcGYbJ5i7pXnJncN7qMs3k_kC2syJ #=zSo26dSS0rx13, System.Collections.Generic.List`1[#=zQnux$qFWIPzYH37I8KXNiSE=]& #=zkmGBR6r5lpk6) (at <0a84c34a447f479815da7957e295d17d>:0)
#=zg_cDRTM6LUoTEaKSYiNc05U=.#=zXUZpJUA= (System.Collections.Generic.List`1[T] #=z5CWZo9sV$NwhPx5Seg==, Microsoft.Geospatial.MercatorBoundingBox #=zPOfo9zdtYUAyZC$c0cQAzik=, System.Nullable`1[T] #=zJMentMFTtCMhtsAg03VV2WxvNIdi, System.Single #=zZ9irFaXT3mIJ, System.Single #=zYvDsJKEuDzWN, Microsoft.Maps.Unity.MapTerrainType #=zcA9qADKGIM27gLWZCw==, Microsoft.Maps.Unity.TextureTileLayerList #=zSAK7PX$HjrRx, Microsoft.Maps.Unity.ElevationTileLayerList #=zh6sd$Irnnd94JYsK9RIzovE=, #=zcGYbJ5i7pXnJncN7qMs3k_kC2syJ #=zSo26dSS0rx13) (at <0a84c34a447f479815da7957e295d17d>:0)
Microsoft.Maps.Unity.MapRendererBase.#=zJ7IPE5U= () (at <0a84c34a447f479815da7957e295d17d>:0)
Microsoft.Maps.Unity.MapRendererBase.Update () (at <0a84c34a447f479815da7957e295d17d>:0)
Microsoft.Maps.Unity.MapRenderer.Update () (at Library/PackageCache/com.microsoft.maps.unity@0.9.1/Runtime/Scripts/MapRenderer/MapRenderer.cs:269)

**To Reproduce**
1. Use version 2020.1.1f1
2. Add MapRenderer to a gameobject.

**Expected behavior**
Does not show this error.

**Environment (please complete the following information):**
 - Unity version: 2020.1.1f1
 - Maps SDK Version 0.9.1

**Comment by visose** [comment]
Looks like this issue was raised here: https://github.com/microsoft/MapsSDK-Unity/issues/82

**Comment by kircher1** [comment]
Fixed in 0.9.2.
