### ISSUE TITLE
MapRendererRaycastHit.location should contain street address and ideally landmark/building name (not just latlon) 

### ISSUE THREAD

**Issue by yosun** [microsoft/MapsSDK-Unity#88]
**Is your feature request related to a problem? Please describe.**
MapRendererRaycastHit.location should contain street address and ideally landmark/building name (not just latlon) 

**Describe the solution you'd like**
As an optional setting in MapRenderer for verbose location info: 

- MapRendererRaycastHit.location.Address could contain the address info 
- MapRendererRaycastHit.location.DisplayName could contain the building or landmark name  
- MapRendererRaycastHit.location.AltName could contain the alternative building or landmark name 

 

**Describe alternatives you've considered**
Currently, this requires making an extra (time-expensive/API-resource-limit expensive) call to  MapLocationFinder.FindLocationsAt(latlon) each time the raycast hit is done.

**Comment by kircher1** [comment]
This address geocoding data isn't available directly on the client hence why the MapLocationFinder service request is necessary. That's not possible to workaround.

I suppose a helper/extension method could be created to do a Raycast + async call into MapLocationFinder, but it's probably clearer to keep them separated.
