### ISSUE TITLE
Redraw tiles during runtime?

### ISSUE THREAD

**Issue by LefanTan** [microsoft/MapsSDK-Unity#89]
Hey, I currently have a custom TextureTileLayer with a URI that might change during runtime. However, when I change the uri, the map doesn't update with the new tilesets. 

Is there an event/function somewhere that I can invoke during runtime to reflect the changes? Thanks!

**Comment by kircher1** [comment]
Calling SetDirty() on the TextureTileLayer should cause a reload. Take a look at how HttpTextureTileLayer is implemented [here](https://github.com/microsoft/MapsSDK-Unity/blob/master/SupportingScripts/Runtime/Scripts/MapRenderer/TextureTileLayers/HttpTextureTileLayer.cs).

**Comment by kircher1** [comment]
Please reopen if that doesn't do the trick, but that should work!

**Comment by LefanTan** [comment]
Hey, it does work for certain cases. However, when pulling raster data, it wouldn't update to new raster images that has the same url. I suspect that there is a caching system that tracks the URL with its images, anyway i could clear up the url's associated cache?
