### ISSUE TITLE
Data is at least 5+ years out of date? Data update?

### ISSUE THREAD

**Issue by yosun** [microsoft/MapsSDK-Unity#90]
**Describe the bug**
Just noticing that the data for San Francisco is missing high rises that were completed in 2015. 

**To Reproduce**
Check out these empty sites: 
Jasper @ 45 Lansing, San Francisco (completed in 2015) 
Mira @ 280 Spear, San Francisco (completed earlier this year) 

**Expected behavior**
They should show the building. 

**Additional context**
When will the data be updated?

**Comment by kircher1** [comment]
This is expected. I don't know of a schedule to share for when that region would be updated.  

Just for some context, this is the same data used by other SDKs like the XAML MapControl for Windows and [Android/iOS SDKs](https://github.com/microsoft/MapsSDK-Native), so the 3D data you are referring to is not specifically utilized by the mapping SDK for Unity. 

If you or your company have a need for fresher data, you could try reaching out to the Bing Maps team through one of [these](https://www.microsoft.com/en-us/maps/support#) channels.
