### ISSUE TITLE
Redraw with SetDirty() doesn't work if the URI doesn't change 

### ISSUE THREAD

**Issue by LefanTan** [microsoft/MapsSDK-Unity#91]
Hey, I found out that SetDirty() does not work properly when the URI I'm calling doesn't change, even though the data at the API end point did. I suspect that there is a caching system associated to the uri, anyway to clear it up?

**Comment by kircher1** [comment]
While tiles are cached by the layer, they are keyed off of their TileId (not the URI actually) and when calling SetDirty(), that cache gets recreated.

I'll confirm this is working though and let you know what I find. Even if the URI doesn't change, after calling SetDirty() on a layer, you should see the textures on the map disappear momentarily as it reloads them.

If this URI a network resource I wonder if there is some lower-level caching happening either in Unity or at the OS layer. If so, you could check the network traffic and see if you are getting responses for the tiles you expect after calling SetDirty().

**Comment by LefanTan** [comment]
I see, i was suspecting that it's keyed to the uri because upon changing the uri's access token, the map properly loads the new textures.

I'll see what I can find with the network traffic. Thank you for the quick response.

**Comment by LefanTan** [comment]
I see, i was suspecting that it's keyed to the uri because upon changing the uri's access token, the map properly loads the new textures.

I'll see what I can find with the network traffic. Thank you for the quick response.

Here's my testing of the SetDirty method. 

![anim](https://user-images.githubusercontent.com/12474777/90176127-bcf79900-dd65-11ea-817c-c3be8b1bcce7.gif)

**Comment by kircher1** [comment]
In my repro case, I'm seeing the network traffic of tiles getting re-requested after dirtying the layer which implies that the client isn't caching anything based on the URI implicitly. In the case I'm looking at, the network requests use http. If you are also using http/https, there are various tools which let you monitor that traffic on your machine. If you can use that approach, you should be able to confirm if the correct image is being requested and returned after dirtying the layer.

**Comment by LefanTan** [comment]
Thank you, I believe that there is an issue from our API endpoint that is causing this confusion, thank you.
