### ISSUE TITLE
CustomTerrainShader Errors: Fails to open source files

### ISSUE THREAD

**Issue by jasonhbartlett** [microsoft/MapsSDK-Unity#92]
Hello,
I'm not sure what happened but the CustomeTerrainShader is giving me a bunch of errors:  See Pic:
![image](https://user-images.githubusercontent.com/22244576/90969293-debef180-e4c4-11ea-976a-f942e91b3de0.png)

According to the .shader file these are supposed to be found in "Packages/com.microsoft.maps.unity/Runtime/Shaders/ClippingVolume-MapsSDK.cginc" however I don't have that directory. 

I have tried removing and re-adding the SDK via package manager.  I have also deleted the entire folder "Assets/Microsoft.Maps.Unity.Examples" folder and copied back that folder over from a fresh clone of the repository.

Please help as the CustomElevationExample scene is now broken in my project.

As a side note: I found this cool free shader on the Unity asset store which I would like to use in my project to create an sonar effect on the map.  [Simple Sonar Shader](https://assetstore.unity.com/packages/vfx/shaders/simple-sonar-shader-102734)  I'm clueless about shaders so would you have any advice about combining this shader with the default terrain shader or the custom terrain shader of the map?  How would I go about doing this, cause it would be a really awesome effect for my project. Thanks!

**Comment by jasonhbartlett** [comment]
Hi @kircher1 
Thanks for your quick response.  Re-importing did do the trick, so thank you!  I wish I understood why.  Why does the path specified not exist and yet it now finds the files? This is confusing to me, but to be honest I know very little about shaders.  I've decided to try and start learning. For now though I'll just have to keep apologizing for my ignorance about shaders.

Regarding the sonar effect, it would be really a nice feature for my project which has the user click on the map, at which point a REST API post is made to a service that ultimately returns back data that we used to generate a custom heatmap tile layer.  But it takes about 30 seconds for the data to come back so I wanted to use the sonar effect as an indicator to the user that the data was processing.  This sonar effect could also be cool to represent earthquake points and magnitudes.

Anyhow, I started by attempting to copy the properties and surf() code directly into a copy of the CustomTerrainShader and so far it hasn't broken it.  (Question, would it be better to try and modify a copy of the StandardTerrainShader-MapsSDK instead?)

The problem I'm currently having is that to trigger the sonar effect I need to access the MapRenderer material directly, but that doesn't seem to be possible?  I need to do something like this:

```csharp
GetComponent<Renderer>().material.SetVectorArray("_hitPts", positionsQueue.ToArray());
GetComponent<Renderer>().material.SetFloatArray("_Intensity", intensityQueue.ToArray());
```
but I'm getting an error that no Renderer exist.  Any help is appreciated.  

PS. I also emailed the author of that Simple Sonar Shader asset to ask if he has any advice as he works for Microsoft Studios and is involved in AR/VR projects. If it works it would be a nice addition to the MS Maps SDK package.

**Comment by jasonhbartlett** [comment]
Hey @kircher1 so is it possible to set properties of the map renderer material as I'd like to to do above?

**Comment by kircher1** [comment]
I think there's a couple of possible options. One is to add a reference to the custom material you created in your script that updates these properties and instead of using `GetComponent<Renderer>.material...`, you can set the properties on the material directly.

A simpler approach may be to use the `Shader.SetGlobalVectorArray/Shader.SetFloatArray`. That wouldn't require a reference to the material.

**Comment by jasonhbartlett** [comment]
Okay, I'll try one of those approaches.  Thanks!

**Comment by jasonhbartlett** [comment]
Hi @kircher1 I am able to get my custom shader to work using both of your recommended approaches. (Thanks again) I've modified a copy of the existing CustomTerrainShader to make my CustomTerrainMaterial and in the Inspector under Render Settings I can use the checkbox to enable "Use Custom Terrain Material", However that boolean doesn't seem to be exposed in the API?  I'd like to be able to enabled and disable that via script if possible.  It testing in the editor turning on/off does't seem to cause any issues so hopefully this API can be opened ?

**Comment by kircher1** [comment]
I think the lack of a code API is just an oversight and it could be added. Will plan on plumbing that through for the next release.

**Comment by jasonhbartlett** [comment]
Hi @kircher1 - Just a question about that "Use Custom Terrain Material" checkbox.  If I enable that with my custom terrain material, then I lose the visuals from our custom heatmap texture tile layer that we added to the Texture Tile Layers under the Default Texture Tile Layer.  Is there a way to still see my heatmap while having the custom terrain material?

![image](https://user-images.githubusercontent.com/22244576/93625901-a8d03880-f9b0-11ea-8628-e9836ae4ab0f.png)

**Comment by kircher1** [comment]
To support multiple layers, the custom material's shader will need to have the same sort of texture sampling logic as the [default shader](https://github.com/microsoft/MapsSDK-Unity/blob/master/SupportingScripts/Runtime/Shaders/StandardTerrainShader-MapsSDK.shader).

This means having the correct variables defined in the shader and the correct logic in the vertex and fragment shaders as well, but I suggest tracing back from the following block of code in the fragment to see what all is necessary:

                    // Albedo comes from a texture tinted by color
                fixed4 color = tex2D(_MainTex0, i.uv);
                if (_MainTexCount > 1) { color = blend(color, tex2D(_MainTex1, i.uv2)); }
                if (_MainTexCount > 2) { color = blend(color, tex2D(_MainTex2, i.uv3)); }
                if (_MainTexCount > 3) { color = blend(color, tex2D(_MainTex3, i.uv4)); }
                color *= _Color;

`_MainTexCount` is basically the number of texture layers.

Note this logic above would support up to 4 layers. However, if you know the app will just have at most two layers, then you could reduce the number of if-cases and save some instructions/complexity.

**Comment by jasonhbartlett** [comment]
@kircher1  Ah.. now, to begin with I'm using a custom shader that is a surface shader.  ( A modified version of the shader used in the custom elevation example ).  And from what I understand about shaders (which isn't much) surface vs frag/vert shaders work differently.  The logic is quite different.
But looking at my shader, even if its a surface shader I think it might support the same logic regarding this sampling?  If that is the case then I'll try playing around with it.

**Comment by kircher1** [comment]
Yeah, it should be possible to do with a surface shader as well. And actually, that surface shader from the sample project handles up to two texture tile layers. Check that out [here](https://github.com/microsoft/MapsSDK-Unity/blob/master/SampleProject/Assets/Microsoft.Maps.Unity.Examples/CustomElevationExample/Shaders/CustomTerrainShader.shader).
