### ISSUE TITLE
Clipping Shader to the Map Edges.

### ISSUE THREAD

**Issue by huzeyfecoskun** [microsoft/MapsSDK-Unity#94]
i am pinning objects to the map. But when i pan my map i want to clip object with border of maps. When i use custom shader its not working properly. When i use your clipping shader its not clipping object as i want. 

Whats the right way of clipping models with border of map.

Thanks in advance.

**Comment by kircher1** [comment]
You can use [this shader](https://github.com/microsoft/MapsSDK-Unity/blob/master/SampleProject/Assets/Microsoft.Maps.Unity.Examples/CustomElevationExample/Shaders/CustomTerrainShader.shader) from the sample project as an example of how to write a custom shader that performs clipping. Specifically see line 101.

That shader is actually a replacement shader to render the terrain for the map, which is not what you are doing, but it does show how to include a reference to the clipping volume cginc and shows how to call the ClipToVolume method which discards pixels outside of the map's bounds.

Note the expected input vertex should be in world space.
