### ISSUE TITLE
Magic Leap intégration

### ISSUE THREAD

**Issue by QGNGO** [microsoft/MapsSDK-Unity#95]
Hi, i've tried your SDK on my laptop, everything worked fine but when i tried to implement it on a lumin (magic leap) project, i got a build error from the IL2CPP (Intermediate Language To C++) when he tried to convert the netcore interface in C++.

The thing is, i'm no programmer and i do not know what to do in order to solve this (if it's solvable). Do you happen to have any informations that could help me ?

_Failed running C:\Program Files\Unity\Hub\Editor\2020.1.4f1\Editor\Data\il2cpp/build/deploy/netcoreapp3.0/il2cpp.exe --convert-to-cpp --emit-null-checks --enable-stacktrace --enable-array-bounds-check --dotnetprofile="unityaot" --compile-cpp --libil2cpp-static --platform="Lumin" --architecture="ARM64" --configuration="Release" --outputpath="C:\Users\qgngo\Desktop\Work_Folder_Unity\Projects\UnityTemplate-0.24.2\Temp/StagingArea/Data\Native\libil2cpp.so" --cachedirectory="C:\Users\qgngo\Desktop\Work_Folder_Unity\Projects\UnityTemplate-0.24.2\Assets\..\Library\il2cpp_cache/il2cpp_cache" --baselib-directory="C:/Program Files/Unity/Hub/Editor/2020.1.4f1/Editor/Data/PlaybackEngines/LuminSupport\Variations/il2cpp/Release/arm64" --avoid-dynamic-library-copy --verbose --enable-stats --stats-output-dir="C:/Users/qgngo/Desktop/Work_Folder_Unity/Projects/UnityTemplate-0.24.2/Assets/../Library/il2cpp_stats" --profiler-report --map-file-parser="C:/Program Files/Unity/Hub/Editor/2020.1.4f1/Editor/Data/Tools/MapFileParser/MapFileParser.exe" --directory=C:/Users/qgngo/Desktop/Work_Folder_Unity/Projects/UnityTemplate-0.24.2/Temp/StagingArea/Data/Managed --generatedcppdir=C:/Users/qgngo/Desktop/Work_Folder_Unity/Projects/UnityTemplate-0.24.2/Temp/StagingArea/Data/il2cppOutput _

**Comment by kircher1** [comment]
The SDK should work with IL2CPP although I don't know if there is any specific to Magic Leap which would prevent it from working. I have not tried a Magic Leap build myself.

A couple of questions to narrow this down:
* Which version of Unity are you using?
* Is there more messaging related to that error? I don't see any clues in that line of log text.

**Comment by QGNGO** [comment]
I also got that message from the same build error, does that help ?

_Exception: C:\Program Files\Unity\Hub\Editor\2020.1.4f1\Editor\Data\il2cpp/build/deploy/netcoreapp3.0/il2cpp.exe did not run properly!
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at <3b1af5075b0340cfb428dfcef292b2ea>:0)
UnityEditorInternal.Runner.RunNetCoreProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at <3b1af5075b0340cfb428dfcef292b2ea>:0)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo, System.String workingDirectory) (at <3b1af5075b0340cfb428dfcef292b2ea>:0)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (UnityEditor.Il2Cpp.Il2CppBuildPipelineData data, System.String outputDirectory, System.String workingDirectory, System.Boolean platformSupportsManagedDebugging) (at <3b1af5075b0340cfb428dfcef292b2ea>:0)
UnityEditorInternal.IL2CPPBuilder.Run () (at <3b1af5075b0340cfb428dfcef292b2ea>:0)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at <3b1af5075b0340cfb428dfcef292b2ea>:0)
UnityEditor.Lumin.PostProcessor.Tasks.IL2CPPCodeGenTask.Execute (UnityEditor.Lumin.PostProcessor.PostProcessorContext ctx) (at C:/buildslave/unity/build/PlatformDependent/Lumin/Editor/Managed/PostProcessor/Tasks/IL2CPPCodeGenTask.cs:46)
UnityEditor.Lumin.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Lumin.PostProcessor.PostProcessorContext context) (at C:/buildslave/unity/build/PlatformDependent/Lumin/Editor/Managed/PostProcessor/PostProcessRunner.cs:27)
UnityEditor.Lumin.PostProcessLumin.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, System.Boolean incremental) (at C:/buildslave/unity/build/PlatformDependent/Lumin/Editor/Managed/PostProcessLumin.cs:91)
Rethrow as UnityException: [Build failure] C:/Program Files/Unity/Hub/Editor/2020.1.4f1/Editor/Data/il2cpp/build/deploy/netcoreapp3.0/il2cpp.exe did not run properly! See the Console for details.
UnityEditor.Lumin.Utils.DialogHelper.Fatal (System.String title, System.String message, System.Exception inner) (at C:/buildslave/unity/build/PlatformDependent/Lumin/Editor/Managed/Utils/DialogHelper.cs:23)
UnityEditor.Lumin.PostProcessLumin.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, System.Boolean incremental) (at C:/buildslave/unity/build/PlatformDependent/Lumin/Editor/Managed/PostProcessLumin.cs:105)
UnityEditor.Lumin.LuminBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/Lumin/Editor/Managed/ExtensionModule.cs:65)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <3b1af5075b0340cfb428dfcef292b2ea>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <3b1af5075b0340cfb428dfcef292b2ea>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)_

**Comment by kircher1** [comment]
I found the root cause of this error is that the native plugins which the SDK uses are not compatible with the Magic Leap platform. The IL2CPP build is erroring because it cannot find the native plugin implementations to link against.

Currently the SDK supports Unity's Android, iOS, Windows Standalone, and UWP platforms. So unfortunately, it won't be possible to build the SDK using the Magic Leap platform in Unity.

**Comment by QGNGO** [comment]
> I found the root cause of this error is that the native plugins which the SDK uses are not compatible with the Magic Leap platform. The IL2CPP build is erroring because it cannot find the native plugin implementations to link against.
> 
> Currently the SDK supports Unity's Android, iOS, Windows Standalone, and UWP platforms. So unfortunately, it won't be possible to build the SDK using the Magic Leap platform in Unity.

Sorry for the late reply, but thank you for your help and the time you spend looking for an answer.
