### ISSUE TITLE
How it is different from Flight simulator sdk?

### ISSUE THREAD

**Issue by jascodes** [microsoft/MapsSDK-Unity#96]
I am exporing prototyping product related to real estate. I was looking for high resolution data like flight sim for show area to clients in VR. I am little confused if there is one or two api's? Flight sim API separate product? 

PS: Sorry for silly question; just get myself orientated.

**Comment by kircher1** [comment]
Right, flight sim is a separate product. It is not related to this SDK. This SDK is a good candidate though to visualize high level of detail data in VR, e.g. for real estate exploration. There is ~400 cities with high res 3D mesh coverage. In areas where we aren't able to provide that level of detail, we have an elevation layer at varying resolutions that covers the globe with high resolution satellite imagery.

Hope that helps!
