### ISSUE TITLE
Any way to access the material of the map renderer?

### ISSUE THREAD

**Issue by LefanTan** [microsoft/MapsSDK-Unity#97]
Hi, I've attached a map to a Unity MRTK UI canvas in worldspace, and in order to create a fade in and out animation, I need to access the alpha value of the map renderer/map and change its value. 

Is there anyway to do? Thanks!

**Comment by kircher1** [comment]
The default shader used for the map does not support transparency and enabling transparency requires modifications to the shader. Specifically, I believe it requires modifying the shader to look like this:

    Tags {"Queue"="Transparent" "RenderType"="Transparent"}

There maybe other things to add like blending equation and zwrite. I'm not entirely sure but Unity probably has some samples.

So to support fading, you'd need to copy the default map shader, modify it to support transparency, and create a new material based on that. Then the new material can be associated with the MapRenderer. The default shader for the map is found under the SDK package. From Unity, you can find it in the assets here: `Packages/Maps SDK for Unity/Runtime/Shaders/StandardTerrainShader-MapsSDK.shader`

**Comment by LefanTan** [comment]
Thank for responding, I do wonder how can I associate this new material with the map renderer?

**Comment by kircher1** [comment]
Check out the `Render Settings` in MapRenderer component. Then check `Use Custom Terrain Material`. That should give you a field for a custom material. https://github.com/microsoft/MapsSDK-Unity/wiki/Configuring-the-MapRenderer#render-settings

In code, you can also set the `MapRenderer.TerrainMaterial` property if it is easier to do it through a script.

**Comment by LefanTan** [comment]
Hey, I think i might have phrased my question wrongly. Right now, I'm trying to take a screenshot of the map by saving the texture showing on the map. I thought to query the material/texture of the map renderer to access the pixels but not sure how.

**Comment by kircher1** [comment]
Ah, that isn't possible by using the Material associated with the MapRenderer. The map uses the lower level Unity graphics API to render it's content. The material specified to the MapRednerer is more like a template that is used to draw the content. Completely rendering the map usually consists of multiple draw calls (i.e., there are multiple textures for a given view, not just 1 texture).
