### ISSUE TITLE
REST API for buildings and other 3D models

### ISSUE THREAD

**Issue by daktor** [microsoft/MapsSDK-Unity#98]
Hi all,

Thanks for pushing this out to the community!  I really like how it pulls down the 3D building models.  I looked through the Bing Maps API and found a REST endpoint for imagery and heightmap:

**imagery:** https://dev.virtualearth.net/REST/v1/Imagery
**heightmap:** http://dev.virtualearth.net/REST/v1/Elevation

Is there a REST endpoint for 3D models such as buildings?

Thanks!

**Comment by kircher1** [comment]
Hello! This SDK uses a mixture of publicly available REST endpoints, e.g. for imagery, as well as endpoints which are not available for direct consumption, e.g. 3d building models. So to answer your question, there is not a corresponding REST endpoint available for that type of data.
