### ISSUE TITLE
Connecting to other raster map server

### ISSUE THREAD

**Issue by YohanBaillot** [microsoft/MapsSDK-Unity#99]
We want to add raster and vector layers to our map. We see there is a TextureTileLayer component that we can add to the map, but the documentation is fuzzy about what this address looks like without a concrete example

The documentation for TextureTileLayer (https://github.com/microsoft/MapsSDK-Unity/wiki/TextureTileLayer) is saying to use a URL with this placeholder http://www.<web service name>.com/{x}/{y}/{zoomlevel}, but what are the parameter to change with their corresponding value and what are the one to use as is?  This is not made clear. Is the URL supposed to follow this exact format X/Y/Zoom or is the format hereunder (Zoom/X/Y) acceptable? 

This page https://docs.microsoft.com/en-us/bingmaps/v8-web-control/map-control-concepts/layers/x-y-zoom-tilelayer related to the native Bing map seems to suggest that the address https://mesonet.agron.iastate.edu/cache/tile.py/1.0.0/nexrad-n0q-900913/{zoom}/{x}/{y}.png could be such a formatted address but entering this, or without the .png at end of even replacing zoom

Same on this page with Quadkey, seems that URL does not work either
https://www.bing.com/api/maps/sdkrelease/mapcontrol/isdk/tilelayerquadkey

All of these attempt are returning 505 or 404 and no tile is displayed or an exclamation mark

It would be really useful to have at least one simple URL as a reference so we know what the URL should look like

Thanks for clarifying how this component should be used and how it might map to other examples in JS or other using Bingmap as well

**Comment by YohanBaillot** [comment]
I believe I figure it out, one example that works is 
https://mesonet.agron.iastate.edu/cache/tile.py/1.0.0/nexrad-n0q-900913/{zoomLevel}/{x}/{y}, so the same format as on this sample page for the JS API, but replacing zoom by zoomLevel, and leave those parameters (zoomLevel, x, y) exactly as is. This is not really straightforward for people not working with maps tiles and should be clarified

**Comment by kircher1** [comment]
The portions of the string which are surrounded by brackets are basically format specifiers. The SDK is filling these with the appropriate values to a request a specific tile of data.

How you structure the URL string to include these variables depends on the endpoint. In this case, it looks like mesonet URL expects zoomLevel, x, then y. (Quadkeys are a more compact way to represent a zoom/x/y, but again, it would depend on whether or not the endpoint can be requested via quadkey or not.)

Also, `[HttpTextureTileLayer](https://github.com/microsoft/MapsSDK-Unity/blob/master/SupportingScripts/Runtime/Scripts/MapRenderer/TextureTileLayers/HttpTextureTileLayer.cs)` uses `{zoomLevel}` as the docs mention, not `{zoom}`. I suppose we could add `{zoom}` as well to avoid confusion.

**Comment by YohanBaillot** [comment]
Thanks for the explanation!

**Comment by kircher1** [comment]
Docs have been updated and in 10.2, there are a couple of overloads for zoomlevel (zoom, z).
